#!/bin/bash
#
# QCAD startup script - uses binaries with debugging info.
#

UNAME=`uname`
KERNEL=`uname -v`
MACHINE=`uname -m`
OPT1=""
OPT2=""

if [[ "$UNAME" != *Darwin* ]];
then
    # Many Linux distributions try to use a style plugin that
    # is 64bit, links against another version of Qt or is
    # otherwise incompatible:
    OPT1="-style"
    OPT2="plastique"
fi

DIR=${0%/*}/release

# Find binary in Mac OS X application bundle:
if [ $UNAME = "Darwin" ]
then
    binary="$DIR/QCAD.app/Contents/MacOS/QCAD"
else
    binary="$DIR/qcad-bin"
fi

if [[ "$UNAME" != *Darwin* ]];
then
    LD_LIBRARY_PATH="$DIR" "$binary" $OPT1 $OPT2 "$@"
else
    DYLD_LIBRARY_PATH="$DIR" "$binary" $OPT1 $OPT2 "$@"
fi
