// Auto generated by Testing Dashboard
// File        : scripts/Information/InfoArcCircleArea/Tests/InfoArcCircleAreaTest00.js
// Timestamp   : 2021-10-29 11:18:15
// Description : 

include('scripts/Developer/TestingDashboard/TdbTest.js');

function InfoArcCircleAreaTest00() {
    TdbTest.call(this, 'scripts/Information/InfoArcCircleArea/Tests/InfoArcCircleAreaTest00.js');
}

InfoArcCircleAreaTest00.prototype = new TdbTest();

InfoArcCircleAreaTest00.prototype.test00 = function() {
    qDebug('running InfoArcCircleAreaTest00.test00()...');
    this.setUp();
    this.importFile('scripts/Information/InfoArcCircleArea/Tests/data/ellipse_area.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::InformationToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::InformationToolsPanel::InfoArcCircleAreaButton');
    this.setToolOption('Information/AddToDrawing', 'true');
    this.setToolOption('Information/TextHeight', '2');
    this.setToolOption('InfoArcCircleArea/Mode', 'Segment');
    this.setToolOption('InfoArcCircleArea/Entity', 'false');
    this.setToolOption('InfoArcCircleArea/Chord', 'false');
    this.setToolOption('InfoArcCircleArea/Length', 'false');
    this.updateToolOptions();
    this.setToolOption('Information/AddToDrawing', 'true');
    this.setToolOption('Information/TextHeight', '2');
    this.setToolOption('InfoArcCircleArea/Mode', 'Segment');
    this.setToolOption('InfoArcCircleArea/Entity', 'false');
    this.setToolOption('InfoArcCircleArea/Chord', 'false');
    this.setToolOption('InfoArcCircleArea/Length', 'false');
    this.updateToolOptions();
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(195.381466, 125.809267);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(208.040948, 100.202586);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(215.521552, 70.855603);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(223.577586, 38.056034);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(222.71444, 8.709052);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(214.658405, -19.487069);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(213.219828, -49.984914);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setToolOption('Information/AddToDrawing', 'true');
    this.setToolOption('Information/TextHeight', '2');
    this.setToolOption('InfoArcCircleArea/Mode', 'Sector');
    this.setToolOption('InfoArcCircleArea/Entity', 'false');
    this.setToolOption('InfoArcCircleArea/Chord', 'false');
    this.setToolOption('InfoArcCircleArea/Length', 'false');
    this.updateToolOptions();
    this.setToolOption('Information/AddToDrawing', 'true');
    this.setToolOption('Information/TextHeight', '2');
    this.setToolOption('InfoArcCircleArea/Mode', 'Sector');
    this.setToolOption('InfoArcCircleArea/Entity', 'false');
    this.setToolOption('InfoArcCircleArea/Chord', 'false');
    this.setToolOption('InfoArcCircleArea/Length', 'false');
    this.updateToolOptions();
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(44.043103, 113.725216);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(43.179957, 98.476293);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(39.727371, 70.280172);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(44.618534, 38.34375);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(42.31681, 9.284483);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(40.302802, -20.637931);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(3.4756554307116105, new RVector(21.556034482758605,77.31788793103445));
    var p = new RVector(39.727371, -49.697198);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(15.271552, 28.273707);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(13.832974, 29.712284);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('InfoArcCircleAreaTest00_000.dxf');
    this.tearDown();
    qDebug('finished InfoArcCircleAreaTest00.test00()');
};

