// Auto generated by Testing Dashboard
// File        : scripts/Modify/AutoTrim/Tests/AutoTrimTest07.js
// Timestamp   : 2017-07-20 16:06:26
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function AutoTrimTest07() {
    TdbTest.call(this, 'scripts/Modify/AutoTrim/Tests/AutoTrimTest07.js');
}

AutoTrimTest07.prototype = new TdbTest();

AutoTrimTest07.prototype.test00 = function() {
    qDebug('running AutoTrimTest07.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/AutoTrim/Tests/data/line.dxf');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::ModifyToolsPanel::AutoTrimButton');
    this.setZoom(5.580071174377224, new RVector(-2.67092, 4.60523, 0, true));
    var p = new RVector(42, 48);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(57.688138, 57.04273);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(68.440689, 56.505102);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('AutoTrimTest07_000.dxf');
    this.tearDown();
    qDebug('finished AutoTrimTest07.test00()');
};

