// Auto generated by Testing Dashboard
// File        : scripts/Modify/AutoTrim/Tests/AutoTrimTest09.js
// Timestamp   : 2017-07-21 16:21:12
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function AutoTrimTest09() {
    TdbTest.call(this, 'scripts/Modify/AutoTrim/Tests/AutoTrimTest09.js');
}

AutoTrimTest09.prototype = new TdbTest();

AutoTrimTest09.prototype.test00 = function() {
    qDebug('running AutoTrimTest09.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/AutoTrim/Tests/data/ellipses.dxf');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::ModifyToolsPanel::AutoTrimButton');
    this.setZoom(7.005402389224175, new RVector(-10.1736, -10.5995, 0, true));
    var p = new RVector(33.869592, 33.581774);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(7.005402389224175, new RVector(-10.1736, -10.5995, 0, true));
    var p = new RVector(41.006941, 37.57869);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(7.005402389224175, new RVector(-10.1736, -10.5995, 0, true));
    var p = new RVector(48.858024, 43.71681);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(7.005402389224175, new RVector(-10.1736, -10.5995, 0, true));
    var p = new RVector(54.71065, 47.713725);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(7.005402389224175, new RVector(-10.1736, -10.5995, 0, true));
    var p = new RVector(59.706794, 49.283942);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(69.128095, 62.416663);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(68.699854, 62.416663);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('AutoTrimTest09_000.dxf');
    this.tearDown();
    qDebug('finished AutoTrimTest09.test00()');
};

