/**
 * Copyright (c) 2011-2018 by Andrew Mustun. All rights reserved.
 * 
 * This file is part of the QCAD project.
 *
 * QCAD is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QCAD is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with QCAD.
 */
// Auto generated by Testing Dashboard
// File        : scripts/Modify/Explode/Tests/ExplodeTest05.js
// Timestamp   : 2011-07-28 15:27:20
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function ExplodeTest05() {
    TdbTest.call(this, 'scripts/Modify/Explode/Tests/ExplodeTest05.js');
}

ExplodeTest05.prototype = new TdbTest();

ExplodeTest05.prototype.test00 = function() {
    qDebug('running ExplodeTest05.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/Explode/Tests/data/block_attrib.dxf');
    this.selectAll();
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::ExplodeButton');
    this.verifyDrawing('ExplodeTest05_000.dxf');
    this.tearDown();
    qDebug('finished ExplodeTest05.test00()');
};

