// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest166.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on circle + polyc, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest166() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest166.js');
}

BreakOutTest166.prototype = new TdbTest();

BreakOutTest166.prototype.test00 = function() {
    qDebug('running BreakOutTest166.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_circle_polyc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(10, 18.385114000948402);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest166_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest166.test00()');
};
