// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest189.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on ellipse + splineo, click entity 0 region 1

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest189() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest189.js');
}

BreakOutTest189.prototype = new TdbTest();

BreakOutTest189.prototype.test00 = function() {
    qDebug('running BreakOutTest189.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_ellipse_splineo.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(9.764676968940798, 16.492137413064768);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest189_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest189.test00()');
};
