// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest137.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on arc + splinec, click entity 0 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest137() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest137.js');
}

BreakOutTest137.prototype = new TdbTest();

BreakOutTest137.prototype.test00 = function() {
    qDebug('running BreakOutTest137.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_arc_splinec.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(5.672008091401196, 14.675720856291811);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest137_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest137.test00()');
};
