// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest181.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on earc + polyo, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest181() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest181.js');
}

BreakOutTest181.prototype = new TdbTest();

BreakOutTest181.prototype.test00 = function() {
    qDebug('running BreakOutTest181.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_earc_polyo.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(4.553023856857487, 13.915161829028023);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest181_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest181.test00()');
};
