// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest145.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on arc + polyc, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest145() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest145.js');
}

BreakOutTest145.prototype = new TdbTest();

BreakOutTest145.prototype.test00 = function() {
    qDebug('running BreakOutTest145.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_arc_polyc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(27.735056458344953, 12.11775268518002);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest145_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest145.test00()');
};
