// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest168.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on earc + earc, click entity 0 region 1

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest168() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest168.js');
}

BreakOutTest168.prototype = new TdbTest();

BreakOutTest168.prototype.test00 = function() {
    qDebug('running BreakOutTest168.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_earc_earc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(15, 11.5);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest168_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest168.test00()');
};
