// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest226.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on polyo + polyc, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest226() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest226.js');
}

BreakOutTest226.prototype = new TdbTest();

BreakOutTest226.prototype.test00 = function() {
    qDebug('running BreakOutTest226.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_polyo_polyc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(21.785714285714285, 7.857142857142857);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest226_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest226.test00()');
};
