// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest132.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on arc + ellipse, click entity 0 region 1

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest132() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest132.js');
}

BreakOutTest132.prototype = new TdbTest();

BreakOutTest132.prototype.test00 = function() {
    qDebug('running BreakOutTest132.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_arc_ellipse.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(15, 20);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest132_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest132.test00()');
};
