// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest223.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on polyo + polyo, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest223() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest223.js');
}

BreakOutTest223.prototype = new TdbTest();

BreakOutTest223.prototype.test00 = function() {
    qDebug('running BreakOutTest223.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_polyo_polyo.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(4.071428571428572, 14.685714285714285);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest223_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest223.test00()');
};
