// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest217.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on splinec + polyo, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest217() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest217.js');
}

BreakOutTest217.prototype = new TdbTest();

BreakOutTest217.prototype.test00 = function() {
    qDebug('running BreakOutTest217.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_splinec_polyo.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(3.2954647112194193, 15.927256462048929);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest217_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest217.test00()');
};
