// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest178.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on earc + splinec, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest178() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest178.js');
}

BreakOutTest178.prototype = new TdbTest();

BreakOutTest178.prototype.test00 = function() {
    qDebug('running BreakOutTest178.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_earc_splinec.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(19.958955861049887, 20.385779682334544);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest178_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest178.test00()');
};
