// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest19.js
// Timestamp   : 2026-06-19
// Description : 

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest19() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest19.js');
}

BreakOutTest19.prototype = new TdbTest();

BreakOutTest19.prototype.test00 = function() {
    qDebug('running BreakOutTest19.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/arc_line.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(4.2, 8.95);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest19_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest19.test00()');
};

