// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest10.js
// Timestamp   : 2016-12-21 15:05:44
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest10() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest10.js');
}

BreakOutTest10.prototype = new TdbTest();

BreakOutTest10.prototype.test00 = function() {
    qDebug('running BreakOutTest10.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/closed_polyline.dxf');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::ModifyToolsPanel::BreakOutButton');
    this.setToolOption('BreakOut/RemoveSegment', 'true');
    this.updateToolOptions();
    this.setZoom(11.789473684210526, new RVector(-32.2321, -38.7545, 0, true));
    var p = new RVector(76.084821, 68.78125);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(51.825893, 60.044643);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(51.825893, 60.299107);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('BreakOutTest10_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest10.test00()');
};

