// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest211.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on splineo + polyc, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest211() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest211.js');
}

BreakOutTest211.prototype = new TdbTest();

BreakOutTest211.prototype.test00 = function() {
    qDebug('running BreakOutTest211.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_splineo_polyc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(27.694793961796577, 12.13564712809041);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest211_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest211.test00()');
};
