// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest139.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on arc + splinec, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest139() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest139.js');
}

BreakOutTest139.prototype = new TdbTest();

BreakOutTest139.prototype.test00 = function() {
    qDebug('running BreakOutTest139.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_arc_splinec.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(25.571213450985834, 18.05126573002411);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest139_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest139.test00()');
};
