// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest184.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on earc + polyc, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest184() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest184.js');
}

BreakOutTest184.prototype = new TdbTest();

BreakOutTest184.prototype.test00 = function() {
    qDebug('running BreakOutTest184.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_earc_polyc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(17.10710689588702, 16.84128582405021);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest184_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest184.test00()');
};
