// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest104.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on line + circle, click entity 0 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest104() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest104.js');
}

BreakOutTest104.prototype = new TdbTest();

BreakOutTest104.prototype.test00 = function() {
    qDebug('running BreakOutTest104.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_line_circle.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(0.75, 10);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest104_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest104.test00()');
};
