// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest136.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on arc + splineo, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest136() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest136.js');
}

BreakOutTest136.prototype = new TdbTest();

BreakOutTest136.prototype.test00 = function() {
    qDebug('running BreakOutTest136.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_arc_splineo.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(3.32367290560845, 16.054275599824923);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest136_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest136.test00()');
};
