// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest134.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on arc + splineo, click entity 0 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest134() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest134.js');
}

BreakOutTest134.prototype = new TdbTest();

BreakOutTest134.prototype.test00 = function() {
    qDebug('running BreakOutTest134.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_arc_splineo.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(4.178294839694857, 8.66486139115028);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest134_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest134.test00()');
};
