// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest187.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on ellipse + ellipse, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest187() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest187.js');
}

BreakOutTest187.prototype = new TdbTest();

BreakOutTest187.prototype.test00 = function() {
    qDebug('running BreakOutTest187.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_ellipse_ellipse.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(9.000000000000004, 9.999999573854991);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest187_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest187.test00()');
};
