// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest129.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on arc + earc, click entity 0 region 1

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest129() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest129.js');
}

BreakOutTest129.prototype = new TdbTest();

BreakOutTest129.prototype.test00 = function() {
    qDebug('running BreakOutTest129.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_arc_earc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(15, 20);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest129_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest129.test00()');
};
