// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest215.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on splinec + polyo, click entity 0 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest215() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest215.js');
}

BreakOutTest215.prototype = new TdbTest();

BreakOutTest215.prototype.test00 = function() {
    qDebug('running BreakOutTest215.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_splinec_polyo.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(12.359763744394764, 17.76415976247993);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest215_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest215.test00()');
};
