// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest124.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on line + polyc, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest124() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest124.js');
}

BreakOutTest124.prototype = new TdbTest();

BreakOutTest124.prototype.test00 = function() {
    qDebug('running BreakOutTest124.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_line_polyc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(16.07833945422946, 17.29851579812024);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest124_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest124.test00()');
};
