// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest200.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on splineo + splineo, click entity 0 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest200() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest200.js');
}

BreakOutTest200.prototype = new TdbTest();

BreakOutTest200.prototype.test00 = function() {
    qDebug('running BreakOutTest200.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_splineo_splineo.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(2.1181991380902154, 8.339301388022484);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest200_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest200.test00()');
};
