// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest176.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on earc + splinec, click entity 0 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest176() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest176.js');
}

BreakOutTest176.prototype = new TdbTest();

BreakOutTest176.prototype.test00 = function() {
    qDebug('running BreakOutTest176.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_earc_splinec.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(25.705517844784566, 7.264109140363208);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest176_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest176.test00()');
};
