// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest199.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on ellipse + polyc, click entity 1 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest199() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest199.js');
}

BreakOutTest199.prototype = new TdbTest();

BreakOutTest199.prototype.test00 = function() {
    qDebug('running BreakOutTest199.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_ellipse_polyc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(26.308992135420706, 10.872661423613804);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest199_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest199.test00()');
};
