// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest206.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on splineo + polyo, click entity 0 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest206() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest206.js');
}

BreakOutTest206.prototype = new TdbTest();

BreakOutTest206.prototype.test00 = function() {
    qDebug('running BreakOutTest206.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_splineo_polyo.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(2.251627904491067, 8.710889870904237);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest206_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest206.test00()');
};
