// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest177.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on earc + splinec, click entity 0 region 1

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest177() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest177.js');
}

BreakOutTest177.prototype = new TdbTest();

BreakOutTest177.prototype.test00 = function() {
    qDebug('running BreakOutTest177.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_earc_splinec.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(17.650313842674755, 11.337973317077527);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest177_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest177.test00()');
};
