// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest225.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on polyo + polyc, click entity 0 region 1

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest225() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest225.js');
}

BreakOutTest225.prototype = new TdbTest();

BreakOutTest225.prototype.test00 = function() {
    qDebug('running BreakOutTest225.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_polyo_polyc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(14.285714285714285, 10.857142857142858);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest225_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest225.test00()');
};
