// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest173.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on earc + splineo, click entity 0 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest173() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest173.js');
}

BreakOutTest173.prototype = new TdbTest();

BreakOutTest173.prototype.test00 = function() {
    qDebug('running BreakOutTest173.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_earc_splineo.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(22.368378416590822, 10.083717653986332);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest173_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest173.test00()');
};
