// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest138.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on arc + splinec, click entity 0 region 1

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest138() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest138.js');
}

BreakOutTest138.prototype = new TdbTest();

BreakOutTest138.prototype.test00 = function() {
    qDebug('running BreakOutTest138.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_arc_splinec.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(22.14166199987416, 17.31269483938155);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest138_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest138.test00()');
};
