// Auto generated by Testing Dashboard
// File        : scripts/Modify/BreakOut/Tests/BreakOutTest131.js
// Timestamp   : 2026-08-25
// Description : BreakOutPro on arc + ellipse, click entity 0 region 0

include('scripts/Developer/TestingDashboard/TdbTest.js');

function BreakOutTest131() {
    TdbTest.call(this, 'scripts/Modify/BreakOut/Tests/BreakOutTest131.js');
}

BreakOutTest131.prototype = new TdbTest();

BreakOutTest131.prototype.test00 = function() {
    qDebug('running BreakOutTest131.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/BreakOut/Tests/data/pair_arc_ellipse.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BreakOutProButton');
    this.setToolOption('BreakOutPro/RemoveSegment', 'true');
    this.setToolOption('BreakOutPro/LineMode', 'false');
    this.updateToolOptions();
    var p = new RVector(5.063257299569713, 13.482017824632436);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BreakOutTest131_000.dxf');
    this.tearDown();
    qDebug('finished BreakOutTest131.test00()');
};
