// Auto generated by Testing Dashboard
// File        : scripts/Draw/Text/Tests/Text40.js
// Timestamp   : 2021-02-03
// Description : 

include('scripts/Developer/TestingDashboard/TdbTest.js');

function Text40() {
    TdbTest.call(this, 'scripts/Draw/Text/Tests/Text40.js');
}

Text40.prototype = new TdbTest();

Text40.prototype.test00 = function() {
    qDebug('running Text40.test00()...');
    this.setUp();
    this.importFile('scripts/Draw/Text/Tests/data/text40.dxf');
    this.selectAll();
    this.triggerCommand('explode');
    this.verifyDrawing('Text40_000.dxf');
    this.triggerCommand('explode');
    this.deselectAll();
    this.verifyDrawing('Text40_001.dxf');
    this.tearDown();
    qDebug('finished Text40.test00()');
};

