// Auto generated by Testing Dashboard
// File        : scripts/Draw/Text/Tests/Text06.js
// Timestamp   : 2015-10-05 16:34:35
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function Text06() {
    TdbTest.call(this, 'scripts/Draw/Text/Tests/Text06.js');
}

Text06.prototype = new TdbTest();

Text06.prototype.test00 = function() {
    qDebug('running Text06.test00()...');
    this.setUp();
    this.importFile('scripts/Draw/Text/Tests/data/text06.dxf');
    this.selectAll();
    this.triggerCommand('explode');
    this.verifyDrawing('Text06_000.dxf');
    this.triggerCommand('explode');
    this.deselectAll();
    this.verifyDrawing('Text06_001.dxf');
    this.tearDown();
    qDebug('finished Text06.test00()');
};

