// Auto generated by Testing Dashboard
// File        : scripts/Draw/Text/Tests/Text30.js
// Timestamp   : 2021-02-03
// Description : 

include('scripts/Developer/TestingDashboard/TdbTest.js');

function Text30() {
    TdbTest.call(this, 'scripts/Draw/Text/Tests/Text30.js');
}

Text30.prototype = new TdbTest();

Text30.prototype.test00 = function() {
    qDebug('running Text30.test00()...');
    this.setUp();
    this.importFile('scripts/Draw/Text/Tests/data/text30.dxf');
    this.selectAll();
    this.triggerCommand('explode');
    this.verifyDrawing('Text30_000.dxf');
    this.triggerCommand('explode');
    this.deselectAll();
    this.verifyDrawing('Text30_001.dxf');
    this.tearDown();
    qDebug('finished Text30.test00()');
};

