// Auto generated by Testing Dashboard
// File        : scripts/Draw/Text/Tests/Text10.js
// Timestamp   : 2015-10-05 16:34:35
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function Text10() {
    TdbTest.call(this, 'scripts/Draw/Text/Tests/Text10.js');
}

Text10.prototype = new TdbTest();

Text10.prototype.test00 = function() {
    qDebug('running Text10.test00()...');
    this.setUp();
    this.importFile('scripts/Draw/Text/Tests/data/text10.dxf');
    this.selectAll();
    this.triggerCommand('explode');
    this.verifyDrawing('Text10_000.dxf');
    this.triggerCommand('explode');
    this.deselectAll();
    this.verifyDrawing('Text10_001.dxf');
    this.tearDown();
    qDebug('finished Text10.test00()');
};

