// Auto generated by Testing Dashboard
// File        : scripts/Draw/Text/Tests/Text37.js
// Timestamp   : 2021-02-03
// Description : 

include('scripts/Developer/TestingDashboard/TdbTest.js');

function Text37() {
    TdbTest.call(this, 'scripts/Draw/Text/Tests/Text37.js');
}

Text37.prototype = new TdbTest();

Text37.prototype.test00 = function() {
    qDebug('running Text37.test00()...');
    this.setUp();
    this.importFile('scripts/Draw/Text/Tests/data/text37.dxf');
    this.selectAll();
    this.triggerCommand('explode');
    this.verifyDrawing('Text37_000.dxf');
    this.triggerCommand('explode');
    this.deselectAll();
    this.verifyDrawing('Text37_001.dxf');
    this.tearDown();
    qDebug('finished Text37.test00()');
};

