// Auto generated by Testing Dashboard
// File        : scripts/Draw/Text/Tests/Text38.js
// Timestamp   : 2021-02-03
// Description : 

include('scripts/Developer/TestingDashboard/TdbTest.js');

function Text38() {
    TdbTest.call(this, 'scripts/Draw/Text/Tests/Text38.js');
}

Text38.prototype = new TdbTest();

Text38.prototype.test00 = function() {
    qDebug('running Text38.test00()...');
    this.setUp();
    this.importFile('scripts/Draw/Text/Tests/data/text38.dxf');
    this.selectAll();
    this.triggerCommand('explode');
    this.verifyDrawing('Text38_000.dxf');
    this.triggerCommand('explode');
    this.deselectAll();
    this.verifyDrawing('Text38_001.dxf');
    this.tearDown();
    qDebug('finished Text38.test00()');
};

