// Auto generated by Testing Dashboard
// File        : scripts/Snap/SnapIntersection/Tests/SnapIntersectionTest01.js
// Timestamp   : 2016-02-09 21:13:05
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function SnapIntersectionTest01() {
    TdbTest.call(this, 'scripts/Snap/SnapIntersection/Tests/SnapIntersectionTest01.js');
}

SnapIntersectionTest01.prototype = new TdbTest();

SnapIntersectionTest01.prototype.test00 = function() {
    qDebug('running SnapIntersectionTest01.test00()...');
    this.setUp();
    this.importFile('scripts/Snap/SnapIntersection/Tests/data/arc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::MainToolsPanel::PointToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::PointToolsPanel::Point1PButton');
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(5.279494, 21.622191);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(9.332865, 24.099251);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(14.73736, 24.774813);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(24.195225, 27.026685);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(30.275281, 27.927434);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(48.290262, 29.278558);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(52.794007, 29.503745);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(59.549625, 30.404494);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(79.366105, 27.927434);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(85.671348, 27.251873);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(96.705524, 26.125936);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(104.361891, 24.549625);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.440748440748436, new RVector(5.75468, 24.7664, 0, true));
    var p = new RVector(113.369382, 21.847378);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(107.064139, 1.580524);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(105.938202, 1.13015);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(105.713015, 0.904963);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('SnapIntersectionTest01_000.dxf');
    this.tearDown();
    qDebug('finished SnapIntersectionTest01.test00()');
};

