// Auto generated by Testing Dashboard
// File        : scripts/Snap/SnapIntersection/Tests/SnapIntersectionTest02.js
// Timestamp   : 2016-02-09 21:15:53
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function SnapIntersectionTest02() {
    TdbTest.call(this, 'scripts/Snap/SnapIntersection/Tests/SnapIntersectionTest02.js');
}

SnapIntersectionTest02.prototype = new TdbTest();

SnapIntersectionTest02.prototype.test00 = function() {
    qDebug('running SnapIntersectionTest02.test00()...');
    this.setUp();
    this.importFile('scripts/Snap/SnapIntersection/Tests/data/ellipse.dxf');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::MainToolsPanel::PointToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::PointToolsPanel::Point1PButton');
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(5.019297, 20.960601);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(9.731929, 22.75589);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(14.893383, 23.877945);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(25.21629, 26.570877);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(30.377744, 27.24411);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(49.003859, 29.937043);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(53.043258, 29.937043);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(60.897644, 29.937043);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(79.52376, 28.141754);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(85.807269, 27.917343);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(95.681354, 26.346466);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(103.760151, 24.326767);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(4.456108917243051, new RVector(5.52802, 24.5948, 0, true));
    var p = new RVector(114.531881, 21.185012);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(75.708772, -1.03168);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(75.25995, -1.03168);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('SnapIntersectionTest02_000.dxf');
    this.tearDown();
    qDebug('finished SnapIntersectionTest02.test00()');
};

