// Auto generated by Testing Dashboard
// File        : scripts/Modify/Reverse/Tests/ReverseTest02.js
// Timestamp   : 2022-06-08 15:34:04
// Description : 

include('scripts/Developer/TestingDashboard/TdbTest.js');

function ReverseTest02() {
    TdbTest.call(this, 'scripts/Modify/Reverse/Tests/ReverseTest02.js');
}

ReverseTest02.prototype = new TdbTest();

ReverseTest02.prototype.test00 = function() {
    qDebug('running ReverseTest02.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/Reverse/Tests/data/polyline02.dxf');
    this.selectAll();
    this.triggerCommand('rv');
    this.verifyDrawing('ReverseTest02_000.dxf');
    this.tearDown();
    qDebug('finished ReverseTest02.test00()');
};

