// Auto generated by Testing Dashboard
// File        : scripts/Modify/Reverse/Tests/ReverseTest03.js
// Timestamp   : 2022-07-06
// Description : 

include('scripts/Developer/TestingDashboard/TdbTest.js');

function ReverseTest03() {
    TdbTest.call(this, 'scripts/Modify/Reverse/Tests/ReverseTest03.js');
}

ReverseTest03.prototype = new TdbTest();

ReverseTest03.prototype.test00 = function() {
    qDebug('running ReverseTest03.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/Reverse/Tests/data/polyline03.dxf');
    this.selectAll();
    this.triggerCommand('rv');
    this.verifyDrawing('ReverseTest03_000.dxf');
    this.tearDown();
    qDebug('finished ReverseTest03.test00()');
};

