# DO NOT EDIT - AUTOMATICALLY GENERATED
NAME = scripts
TSDIR = .
include(../shared_ts.pri)
SOURCES = \
../scripts/AddOn.js \
../scripts/Apollonius.js \
../scripts/Block/AddBlock/AddBlock.js \
../scripts/Block/AddBlock/AddBlockInit.js \
../scripts/Block/AddBlock/Tests/AddBlockTest00.js \
../scripts/Block/Block.js \
../scripts/Block/BlockDialog.js \
../scripts/Block/BlockInsert.js \
../scripts/Block/CreateBlock/CreateBlock.js \
../scripts/Block/CreateBlock/CreateBlockInit.js \
../scripts/Block/CreateBlock/Tests/CreateBlockTest00.js \
../scripts/Block/CreateBlock/Tests/CreateBlockTest01.js \
../scripts/Block/CreateBlock/Tests/CreateBlockTest02.js \
../scripts/Block/CreateLibraryItem/CreateLibraryItem.js \
../scripts/Block/CreateLibraryItem/CreateLibraryItemInit.js \
../scripts/Block/DeselectBlockReferences/DeselectBlockReferences.js \
../scripts/Block/DeselectBlockReferences/DeselectBlockReferencesInit.js \
../scripts/Block/EditBlock/EditBlock.js \
../scripts/Block/EditBlock/EditBlockInit.js \
../scripts/Block/EditBlock/Tests/EditBlockTest00.js \
../scripts/Block/EditFromReference/EditFromReference.js \
../scripts/Block/EditFromReference/EditFromReferenceInit.js \
../scripts/Block/EditFromReference/Tests/EditFromReferenceTest00.js \
../scripts/Block/EditMainDrawing/EditMainDrawing.js \
../scripts/Block/EditMainDrawing/EditMainDrawingInit.js \
../scripts/Block/HideAllBlocks/HideAllBlocks.js \
../scripts/Block/HideAllBlocks/HideAllBlocksInit.js \
../scripts/Block/InsertBlock/InsertBlock.js \
../scripts/Block/InsertBlock/InsertBlockInit.js \
../scripts/Block/InsertBlock/Tests/InsertBlockTest00.js \
../scripts/Block/InsertBlock/Tests/InsertBlockTest01.js \
../scripts/Block/InsertBlockItem/InsertBlockItem.js \
../scripts/Block/InsertBlockItem/InsertBlockItemInit.js \
../scripts/Block/InsertScriptItem/InsertScriptItem.js \
../scripts/Block/InsertScriptItem/InsertScriptItemInit.js \
../scripts/Block/RemoveBlock/RemoveBlock.js \
../scripts/Block/RemoveBlock/RemoveBlockInit.js \
../scripts/Block/RemoveBlock/Tests/RemoveBlockTest00.js \
../scripts/Block/RenameBlock/RenameBlock.js \
../scripts/Block/RenameBlock/RenameBlockInit.js \
../scripts/Block/RenameBlock/Tests/RenameBlockTest00.js \
../scripts/Block/SelectBlockReferences/SelectBlockReferences.js \
../scripts/Block/SelectBlockReferences/SelectBlockReferencesInit.js \
../scripts/Block/ShowAllBlocks/ShowAllBlocks.js \
../scripts/Block/ShowAllBlocks/ShowAllBlocksInit.js \
../scripts/Block/ToggleBlockVisibility/ToggleBlockVisibility.js \
../scripts/Block/ToggleBlockVisibility/ToggleBlockVisibilityInit.js \
../scripts/DbConnection.js \
../scripts/DefaultAction.js \
../scripts/Draw/Arc/Arc.js \
../scripts/Draw/Arc/Arc2PA/Arc2PA.js \
../scripts/Draw/Arc/Arc2PA/Arc2PAInit.js \
../scripts/Draw/Arc/Arc2PA/Tests/Arc2PATest00.js \
../scripts/Draw/Arc/Arc2PH/Arc2PH.js \
../scripts/Draw/Arc/Arc2PH/Arc2PHInit.js \
../scripts/Draw/Arc/Arc2PH/Tests/Arc2PHTest00.js \
../scripts/Draw/Arc/Arc2PL/Arc2PL.js \
../scripts/Draw/Arc/Arc2PL/Arc2PLInit.js \
../scripts/Draw/Arc/Arc2PL/Tests/Arc2PLTest00.js \
../scripts/Draw/Arc/Arc2PR/Arc2PR.js \
../scripts/Draw/Arc/Arc2PR/Arc2PRInit.js \
../scripts/Draw/Arc/Arc2PR/Tests/Arc2PRTest00.js \
../scripts/Draw/Arc/Arc3P/Arc3P.js \
../scripts/Draw/Arc/Arc3P/Arc3PInit.js \
../scripts/Draw/Arc/Arc3P/Tests/Arc3PTest00.js \
../scripts/Draw/Arc/ArcCPA/ArcCPA.js \
../scripts/Draw/Arc/ArcCPA/ArcCPAInit.js \
../scripts/Draw/Arc/ArcCPA/Tests/ArcCPATest00.js \
../scripts/Draw/Arc/ArcConcentric/ArcConcentric.js \
../scripts/Draw/Arc/ArcConcentric/ArcConcentricInit.js \
../scripts/Draw/Arc/ArcConcentric/Tests/ArcConcentricTest00.js \
../scripts/Draw/Arc/ArcConcentricThrough/ArcConcentricThrough.js \
../scripts/Draw/Arc/ArcConcentricThrough/ArcConcentricThroughInit.js \
../scripts/Draw/Arc/ArcConcentricThrough/Tests/ArcConcentricThroughTest00.js \
../scripts/Draw/Arc/ArcTPR/ArcTPR.js \
../scripts/Draw/Arc/ArcTPR/ArcTPRInit.js \
../scripts/Draw/Arc/ArcTPR/Tests/ArcTPRTest00.js \
../scripts/Draw/Arc/ArcTangential/ArcTangential.js \
../scripts/Draw/Arc/ArcTangential/ArcTangentialInit.js \
../scripts/Draw/Arc/ArcTangential/Tests/ArcTangentialTest00.js \
../scripts/Draw/Circle/Circle.js \
../scripts/Draw/Circle/Circle2P/Circle2P.js \
../scripts/Draw/Circle/Circle2P/Circle2PInit.js \
../scripts/Draw/Circle/Circle2P/Tests/Circle2PTest00.js \
../scripts/Draw/Circle/Circle2PR/Circle2PR.js \
../scripts/Draw/Circle/Circle2PR/Circle2PRInit.js \
../scripts/Draw/Circle/Circle2PR/Tests/Circle2PRTest00.js \
../scripts/Draw/Circle/Circle2TP/Circle2TP.js \
../scripts/Draw/Circle/Circle2TP/Circle2TPInit.js \
../scripts/Draw/Circle/Circle2TP/Tests/Circle2TPTest00.js \
../scripts/Draw/Circle/Circle2TP/Tests/Circle2TPTest01.js \
../scripts/Draw/Circle/Circle2TP/Tests/Circle2TPTest02.js \
../scripts/Draw/Circle/Circle2TP/Tests/Circle2TPTest03.js \
../scripts/Draw/Circle/Circle2TR/Circle2TR.js \
../scripts/Draw/Circle/Circle2TR/Circle2TRInit.js \
../scripts/Draw/Circle/Circle2TR/Tests/Circle2TRTest00.js \
../scripts/Draw/Circle/Circle2TR/Tests/Circle2TRTest01.js \
../scripts/Draw/Circle/Circle3P/Circle3P.js \
../scripts/Draw/Circle/Circle3P/Circle3PInit.js \
../scripts/Draw/Circle/Circle3P/Tests/Circle3PTest00.js \
../scripts/Draw/Circle/Circle3T/Circle3T.js \
../scripts/Draw/Circle/Circle3T/Circle3TInit.js \
../scripts/Draw/Circle/Circle3T/Tests/Circle3TTest00.js \
../scripts/Draw/Circle/Circle3T/Tests/Circle3TTest01.js \
../scripts/Draw/Circle/Circle3T/Tests/Circle3TTest02.js \
../scripts/Draw/Circle/Circle3T/Tests/Circle3TTest03.js \
../scripts/Draw/Circle/CircleCD/CircleCD.js \
../scripts/Draw/Circle/CircleCD/CircleCDInit.js \
../scripts/Draw/Circle/CircleCD/Tests/CircleCDTest00.js \
../scripts/Draw/Circle/CircleCP/CircleCP.js \
../scripts/Draw/Circle/CircleCP/CircleCPInit.js \
../scripts/Draw/Circle/CircleCP/Tests/CircleCPTest00.js \
../scripts/Draw/Circle/CircleCR/CircleCR.js \
../scripts/Draw/Circle/CircleCR/CircleCRInit.js \
../scripts/Draw/Circle/CircleCR/Tests/CircleCRTest00.js \
../scripts/Draw/Circle/CircleCR/Tests/CircleCRTest01.js \
../scripts/Draw/Circle/CircleConcentric/CircleConcentric.js \
../scripts/Draw/Circle/CircleConcentric/CircleConcentricInit.js \
../scripts/Draw/Circle/CircleConcentric/Tests/CircleConcentricTest00.js \
../scripts/Draw/Circle/CircleConcentricThrough/CircleConcentricThrough.js \
../scripts/Draw/Circle/CircleConcentricThrough/CircleConcentricThroughInit.js \
../scripts/Draw/Circle/CircleConcentricThrough/Tests/CircleConcentricThroughTest00.js \
../scripts/Draw/Circle/CircleT2P/CircleT2P.js \
../scripts/Draw/Circle/CircleT2P/CircleT2PInit.js \
../scripts/Draw/Circle/CircleT2P/Tests/CircleT2PTest00.js \
../scripts/Draw/Circle/CircleTPR/CircleTPR.js \
../scripts/Draw/Circle/CircleTPR/CircleTPRInit.js \
../scripts/Draw/Circle/CircleTPR/Tests/CircleTPRTest00.js \
../scripts/Draw/Dimension/DimAligned/DimAligned.js \
../scripts/Draw/Dimension/DimAligned/DimAlignedInit.js \
../scripts/Draw/Dimension/DimAligned/Tests/DimAlignedTest00.js \
../scripts/Draw/Dimension/DimAngular/DimAngular.js \
../scripts/Draw/Dimension/DimAngular/DimAngularInit.js \
../scripts/Draw/Dimension/DimAngular/Tests/DimAngularTest00.js \
../scripts/Draw/Dimension/DimAngular/Tests/DimAngularTest01.js \
../scripts/Draw/Dimension/DimDiametric/DimDiametric.js \
../scripts/Draw/Dimension/DimDiametric/DimDiametricInit.js \
../scripts/Draw/Dimension/DimDiametric/Tests/DimDiametricTest00.js \
../scripts/Draw/Dimension/DimHorizontal/DimHorizontal.js \
../scripts/Draw/Dimension/DimHorizontal/DimHorizontalInit.js \
../scripts/Draw/Dimension/DimHorizontal/Tests/DimHorizontalTest00.js \
../scripts/Draw/Dimension/DimOrdinate/DimOrdinate.js \
../scripts/Draw/Dimension/DimOrdinate/DimOrdinateInit.js \
../scripts/Draw/Dimension/DimOrdinate/Tests/DimOrdinateTest00.js \
../scripts/Draw/Dimension/DimRadial/DimRadial.js \
../scripts/Draw/Dimension/DimRadial/DimRadialInit.js \
../scripts/Draw/Dimension/DimRadial/Tests/DimRadialTest00.js \
../scripts/Draw/Dimension/DimRegen/DimRegen.js \
../scripts/Draw/Dimension/DimRegen/DimRegenInit.js \
../scripts/Draw/Dimension/DimRotated/DimRotated.js \
../scripts/Draw/Dimension/DimRotated/DimRotatedInit.js \
../scripts/Draw/Dimension/DimRotated/Tests/DimRotatedTest00.js \
../scripts/Draw/Dimension/DimVertical/DimVertical.js \
../scripts/Draw/Dimension/DimVertical/DimVerticalInit.js \
../scripts/Draw/Dimension/DimVertical/Tests/DimVerticalTest00.js \
../scripts/Draw/Dimension/Dimension.js \
../scripts/Draw/Dimension/Leader/Leader.js \
../scripts/Draw/Dimension/Leader/LeaderInit.js \
../scripts/Draw/Dimension/Leader/Tests/LeaderTest00.js \
../scripts/Draw/Draw.js \
../scripts/Draw/DrawBasedOnRectanglePP.js \
../scripts/Draw/DrawBasedOnRectangleSize.js \
../scripts/Draw/DrawBasedOnThreeCircles.js \
../scripts/Draw/Ellipse/Ellipse.js \
../scripts/Draw/Ellipse/EllipseArcCPPA/EllipseArcCPPA.js \
../scripts/Draw/Ellipse/EllipseArcCPPA/EllipseArcCPPAInit.js \
../scripts/Draw/Ellipse/EllipseArcCPPA/Tests/EllipseArcCPPATest00.js \
../scripts/Draw/Ellipse/EllipseCPP/EllipseCPP.js \
../scripts/Draw/Ellipse/EllipseCPP/EllipseCPPInit.js \
../scripts/Draw/Ellipse/EllipseCPP/Tests/EllipseCPPTest00.js \
../scripts/Draw/Ellipse/EllipseDD/EllipseDD.js \
../scripts/Draw/Ellipse/EllipseDD/EllipseDDInit.js \
../scripts/Draw/Ellipse/EllipseDD/Tests/EllipseDDTest00.js \
../scripts/Draw/Ellipse/EllipseInscribedQuad/EllipseInscribedQuad.js \
../scripts/Draw/Ellipse/EllipseInscribedQuad/EllipseInscribedQuadInit.js \
../scripts/Draw/Ellipse/EllipseInscribedQuad/Tests/EllipseInscribedQuadTest00.js \
../scripts/Draw/Ellipse/EllipseOffset/EllipseOffset.js \
../scripts/Draw/Ellipse/EllipseOffset/EllipseOffsetInit.js \
../scripts/Draw/Ellipse/EllipseOffset/Tests/EllipseOffsetTest00.js \
../scripts/Draw/Ellipse/EllipseOffsetThrough/EllipseOffsetThrough.js \
../scripts/Draw/Ellipse/EllipseOffsetThrough/EllipseOffsetThroughInit.js \
../scripts/Draw/Ellipse/EllipseOffsetThrough/Tests/EllipseOffsetThroughTest00.js \
../scripts/Draw/Ellipse/EllipseRR/EllipseRR.js \
../scripts/Draw/Ellipse/EllipseRR/EllipseRRInit.js \
../scripts/Draw/Ellipse/EllipseRR/Tests/EllipseRRTest00.js \
../scripts/Draw/Hatch/Hatch.js \
../scripts/Draw/Hatch/HatchDialog.js \
../scripts/Draw/Hatch/HatchFromSelection/HatchFromSelection.js \
../scripts/Draw/Hatch/HatchFromSelection/HatchFromSelectionInit.js \
../scripts/Draw/Hatch/HatchFromSelection/Tests/HatchFromSelectionTest00.js \
../scripts/Draw/Hatch/HatchFromSelection/Tests/HatchFromSelectionTest01.js \
../scripts/Draw/Hatch/HatchFromSelection/Tests/HatchFromSelectionTest02.js \
../scripts/Draw/Hatch/HatchFromSelection/Tests/HatchFromSelectionTest03.js \
../scripts/Draw/Hatch/HatchFromSelection/Tests/HatchFromSelectionTest04.js \
../scripts/Draw/Hatch/HatchFromSelection/Tests/HatchFromSelectionTest05.js \
../scripts/Draw/Hatch/HatchFromSelection/Tests/HatchFromSelectionTest06.js \
../scripts/Draw/Hatch/HatchFromSelection/Tests/HatchFromSelectionTest07.js \
../scripts/Draw/Hatch/HatchFromSelection/Tests/HatchFromSelectionTest08.js \
../scripts/Draw/Image/Image.js \
../scripts/Draw/Image/ImageInit.js \
../scripts/Draw/Image/Tests/ImageTest00.js \
../scripts/Draw/Line/Line.js \
../scripts/Draw/Line/Line2P/Line2P.js \
../scripts/Draw/Line/Line2P/Line2PInit.js \
../scripts/Draw/Line/Line2P/Tests/Lines00.js \
../scripts/Draw/Line/Line2P/Tests/Lines01.js \
../scripts/Draw/Line/Line2P/Tests/Lines02.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapCenter.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapCoordinate.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapDistance.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapEnd.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapFree.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapGrid.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapIntersection.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapIntersectionBlock.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapMiddle.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapMiddleManual.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapOnEntity.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapPolarCoordinate.js \
../scripts/Draw/Line/Line2P/Tests/LinesSnapReferences.js \
../scripts/Draw/Line/LineAngle/LineAngle.js \
../scripts/Draw/Line/LineAngle/LineAngleInit.js \
../scripts/Draw/Line/LineAngle/Tests/LineAngle00.js \
../scripts/Draw/Line/LineAngle/Tests/LineAngle01.js \
../scripts/Draw/Line/LineAngle/Tests/LineAngle02.js \
../scripts/Draw/Line/LineBisector/LineBisector.js \
../scripts/Draw/Line/LineBisector/LineBisectorInit.js \
../scripts/Draw/Line/LineBisector/Tests/LineBisectorTest00.js \
../scripts/Draw/Line/LineBisector/Tests/LineBisectorTest01.js \
../scripts/Draw/Line/LineFreehand/LineFreehand.js \
../scripts/Draw/Line/LineFreehand/LineFreehandInit.js \
../scripts/Draw/Line/LineHorizontal/LineHorizontal.js \
../scripts/Draw/Line/LineHorizontal/LineHorizontalInit.js \
../scripts/Draw/Line/LineHorizontal/Tests/LineHorizontalTest00.js \
../scripts/Draw/Line/LineOrthogonal/LineOrthogonal.js \
../scripts/Draw/Line/LineOrthogonal/LineOrthogonalInit.js \
../scripts/Draw/Line/LineOrthogonal/Tests/LineOrthogonalTest00.js \
../scripts/Draw/Line/LineOrthogonalTangent/LineOrthogonalTangent.js \
../scripts/Draw/Line/LineOrthogonalTangent/LineOrthogonalTangentInit.js \
../scripts/Draw/Line/LineOrthogonalTangent/Tests/LineOrthogonalTangentTest00.js \
../scripts/Draw/Line/LineParallel/LineParallel.js \
../scripts/Draw/Line/LineParallel/LineParallelInit.js \
../scripts/Draw/Line/LineParallel/Tests/LineParallelTest00.js \
../scripts/Draw/Line/LineParallel/Tests/LineParallelTest01.js \
../scripts/Draw/Line/LineParallelThrough/LineParallelThrough.js \
../scripts/Draw/Line/LineParallelThrough/LineParallelThroughInit.js \
../scripts/Draw/Line/LineParallelThrough/Tests/LineParallelThroughTest00.js \
../scripts/Draw/Line/LineParallelThrough/Tests/LineParallelThroughTest01.js \
../scripts/Draw/Line/LineRelativeAngle/LineRelativeAngle.js \
../scripts/Draw/Line/LineRelativeAngle/LineRelativeAngleInit.js \
../scripts/Draw/Line/LineRelativeAngle/Tests/LineRelativeAngleTest00.js \
../scripts/Draw/Line/LineTangent1/LineTangent1.js \
../scripts/Draw/Line/LineTangent1/LineTangent1Init.js \
../scripts/Draw/Line/LineTangent1/Tests/LineTangent1Test00.js \
../scripts/Draw/Line/LineTangent1/Tests/LineTangent1Test01.js \
../scripts/Draw/Line/LineTangent2/LineTangent2.js \
../scripts/Draw/Line/LineTangent2/LineTangent2Init.js \
../scripts/Draw/Line/LineTangent2/Tests/LineTangent2Test00.js \
../scripts/Draw/Line/LineTangent2/Tests/LineTangent2Test01.js \
../scripts/Draw/Line/LineVertical/LineVertical.js \
../scripts/Draw/Line/LineVertical/LineVerticalInit.js \
../scripts/Draw/Line/LineVertical/Tests/LineVerticalTest00.js \
../scripts/Draw/Point/Point.js \
../scripts/Draw/Point/Point1P/Point1P.js \
../scripts/Draw/Point/Point1P/Point1PInit.js \
../scripts/Draw/Point/Point1P/Tests/Point1PTest00.js \
../scripts/Draw/Polyline/DrawPolyline/DrawPolyline.js \
../scripts/Draw/Polyline/DrawPolyline/DrawPolylineInit.js \
../scripts/Draw/Polyline/DrawPolyline/Tests/DrawPolylineTest00.js \
../scripts/Draw/Polyline/DrawPolyline/Tests/DrawPolylineTest01.js \
../scripts/Draw/Polyline/Polyline.js \
../scripts/Draw/Shape/Shape.js \
../scripts/Draw/Shape/ShapePolygonAFCP/ShapePolygonAFCP.js \
../scripts/Draw/Shape/ShapePolygonAFCP/ShapePolygonAFCPInit.js \
../scripts/Draw/Shape/ShapePolygonAFCP/Tests/ShapePolygonAFCPTest00.js \
../scripts/Draw/Shape/ShapePolygonAFPP/ShapePolygonAFPP.js \
../scripts/Draw/Shape/ShapePolygonAFPP/ShapePolygonAFPPInit.js \
../scripts/Draw/Shape/ShapePolygonAFPP/Tests/ShapePolygonAFPPTest00.js \
../scripts/Draw/Shape/ShapePolygonAFPP/Tests/ShapePolygonAFPPTest01.js \
../scripts/Draw/Shape/ShapePolygonCP/ShapePolygonCP.js \
../scripts/Draw/Shape/ShapePolygonCP/ShapePolygonCPInit.js \
../scripts/Draw/Shape/ShapePolygonCP/Tests/ShapePolygonCPTest00.js \
../scripts/Draw/Shape/ShapePolygonCP/Tests/ShapePolygonCPTest01.js \
../scripts/Draw/Shape/ShapePolygonCP/Tests/ShapePolygonCPTest02.js \
../scripts/Draw/Shape/ShapePolygonPP/ShapePolygonPP.js \
../scripts/Draw/Shape/ShapePolygonPP/ShapePolygonPPInit.js \
../scripts/Draw/Shape/ShapePolygonPP/Tests/ShapePolygonPPTest00.js \
../scripts/Draw/Shape/ShapePolygonPP/Tests/ShapePolygonPPTest01.js \
../scripts/Draw/Shape/ShapePolygonPP/Tests/ShapePolygonPPTest02.js \
../scripts/Draw/Shape/ShapeRectanglePP/ShapeRectanglePP.js \
../scripts/Draw/Shape/ShapeRectanglePP/ShapeRectanglePPInit.js \
../scripts/Draw/Shape/ShapeRectanglePP/Tests/ShapeRectanglePPTest00.js \
../scripts/Draw/Shape/ShapeRectanglePP/Tests/ShapeRectanglePPTest01.js \
../scripts/Draw/Shape/ShapeRectangleSize/ShapeRectangleSize.js \
../scripts/Draw/Shape/ShapeRectangleSize/ShapeRectangleSizeInit.js \
../scripts/Draw/Shape/ShapeRectangleSize/Tests/ShapeRectangleSizeTest00.js \
../scripts/Draw/Shape/ShapeRectangleSize/Tests/ShapeRectangleSizeTest01.js \
../scripts/Draw/Spline/Spline.js \
../scripts/Draw/Spline/SplineControlPoints/SplineControlPoints.js \
../scripts/Draw/Spline/SplineControlPoints/SplineControlPointsInit.js \
../scripts/Draw/Spline/SplineControlPoints/Tests/SplineControlPointsTest00.js \
../scripts/Draw/Text/Tests/Text01.js \
../scripts/Draw/Text/Tests/Text02.js \
../scripts/Draw/Text/Tests/Text03.js \
../scripts/Draw/Text/Tests/Text04.js \
../scripts/Draw/Text/Tests/Text05.js \
../scripts/Draw/Text/Tests/Text06.js \
../scripts/Draw/Text/Tests/Text07.js \
../scripts/Draw/Text/Tests/Text08.js \
../scripts/Draw/Text/Tests/Text09.js \
../scripts/Draw/Text/Tests/Text10.js \
../scripts/Draw/Text/Tests/Text11.js \
../scripts/Draw/Text/Tests/Text12.js \
../scripts/Draw/Text/Tests/Text13.js \
../scripts/Draw/Text/Tests/Text14.js \
../scripts/Draw/Text/Tests/Text15.js \
../scripts/Draw/Text/Tests/Text16.js \
../scripts/Draw/Text/Tests/Text17.js \
../scripts/Draw/Text/Tests/Text18.js \
../scripts/Draw/Text/Tests/Text19.js \
../scripts/Draw/Text/Tests/Text20.js \
../scripts/Draw/Text/Text.js \
../scripts/Draw/Text/TextDialog/CharacterMapDialog.js \
../scripts/Draw/Text/TextDialog/TextDialog.js \
../scripts/Draw/Text/TextInit.js \
../scripts/EAction.js \
../scripts/Edit/AbstractPreferences.js \
../scripts/Edit/AppPreferences/AppPreferences.js \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/BehaviorPreferences/BehaviorPreferences.js \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/BehaviorPreferences/BehaviorPreferencesInit.js \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/ColorPreferences/ColorPreferences.js \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/ColorPreferences/ColorPreferencesInit.js \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/FontPreferences/FontPreferences.js \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/FontPreferences/FontPreferencesInit.js \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/GraphicsViewPreferences.js \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/GridPreferences/GridPreferences.js \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/GridPreferences/GridPreferencesInit.js \
../scripts/Edit/AppPreferences/InputPreferences/InputPreferences.js \
../scripts/Edit/AppPreferences/InputPreferences/InputPreferencesInit.js \
../scripts/Edit/AppPreferences/KeyboardPreferences/KeyboardPreferences.js \
../scripts/Edit/AppPreferences/KeyboardPreferences/KeyboardPreferencesInit.js \
../scripts/Edit/AppPreferences/LanguagePreferences/LanguagePreferences.js \
../scripts/Edit/AppPreferences/LanguagePreferences/LanguagePreferencesInit.js \
../scripts/Edit/AppPreferences/LayerCompatibility/LayerCompatibility.js \
../scripts/Edit/AppPreferences/LayerCompatibility/LayerCompatibilityInit.js \
../scripts/Edit/AppPreferences/ScriptingPreferences/ScriptingPreferences.js \
../scripts/Edit/AppPreferences/ScriptingPreferences/ScriptingPreferencesInit.js \
../scripts/Edit/AppPreferences/TextPreferences/TextPreferences.js \
../scripts/Edit/AppPreferences/TextPreferences/TextPreferencesInit.js \
../scripts/Edit/AppPreferences/ThemePreferences/ThemePreferences.js \
../scripts/Edit/AppPreferences/ThemePreferences/ThemePreferencesInit.js \
../scripts/Edit/AppPreferences/ToolBarPreferences/ToolBarPreferences.js \
../scripts/Edit/AppPreferences/ToolBarPreferences/ToolBarPreferencesInit.js \
../scripts/Edit/AppPreferences/UiPreferences/UiPreferences.js \
../scripts/Edit/AppPreferences/UiPreferences/UiPreferencesInit.js \
../scripts/Edit/ClipboardOperation.js \
../scripts/Edit/ConvertUnit/ConvertUnit.js \
../scripts/Edit/ConvertUnit/ConvertUnitInit.js \
../scripts/Edit/Copy/Copy.js \
../scripts/Edit/Copy/CopyInit.js \
../scripts/Edit/Copy/Tests/CopyTest00.js \
../scripts/Edit/CopyWithReference/CopyWithReference.js \
../scripts/Edit/CopyWithReference/CopyWithReferenceInit.js \
../scripts/Edit/CopyWithReference/Tests/CopyWithReferenceTest00.js \
../scripts/Edit/Cut/Cut.js \
../scripts/Edit/Cut/CutInit.js \
../scripts/Edit/Cut/Tests/CutTest00.js \
../scripts/Edit/CutWithReference/CutWithReference.js \
../scripts/Edit/CutWithReference/CutWithReferenceInit.js \
../scripts/Edit/CutWithReference/Tests/CutWithReferenceTest00.js \
../scripts/Edit/Delete/Delete.js \
../scripts/Edit/Delete/DeleteInit.js \
../scripts/Edit/Delete/Tests/DeleteTest00.js \
../scripts/Edit/DrawingPreferences/ColorSettings/ColorSettings.js \
../scripts/Edit/DrawingPreferences/ColorSettings/ColorSettingsInit.js \
../scripts/Edit/DrawingPreferences/DimensionSettings/DimensionSettings.js \
../scripts/Edit/DrawingPreferences/DimensionSettings/DimensionSettingsInit.js \
../scripts/Edit/DrawingPreferences/DrawingPreferences.js \
../scripts/Edit/DrawingPreferences/GridSettings/GridSettings.js \
../scripts/Edit/DrawingPreferences/GridSettings/GridSettingsInit.js \
../scripts/Edit/DrawingPreferences/LinetypeSettings/LinetypeSettings.js \
../scripts/Edit/DrawingPreferences/LinetypeSettings/LinetypeSettingsInit.js \
../scripts/Edit/DrawingPreferences/PageSettings/PageSettings.js \
../scripts/Edit/DrawingPreferences/PageSettings/PageSettingsInit.js \
../scripts/Edit/DrawingPreferences/PointDisplaySettings/PointDisplaySettings.js \
../scripts/Edit/DrawingPreferences/PointDisplaySettings/PointDisplaySettingsInit.js \
../scripts/Edit/DrawingPreferences/UnitSettings/UnitSettings.js \
../scripts/Edit/DrawingPreferences/UnitSettings/UnitSettingsInit.js \
../scripts/Edit/DrawingPreferences/ViewportSettings/ViewportSettings.js \
../scripts/Edit/DrawingPreferences/ViewportSettings/ViewportSettingsInit.js \
../scripts/Edit/Duplicate/Duplicate.js \
../scripts/Edit/Duplicate/DuplicateInit.js \
../scripts/Edit/Duplicate/Tests/DuplicateTest00.js \
../scripts/Edit/Edit.js \
../scripts/Edit/Esc/Esc.js \
../scripts/Edit/Esc/EscInit.js \
../scripts/Edit/Esc/Tests/EActionTest00.js \
../scripts/Edit/Esc/Tests/EActionTest01.js \
../scripts/Edit/Esc/Tests/EActionTest02.js \
../scripts/Edit/Esc/Tests/EActionTest03.js \
../scripts/Edit/Esc/Tests/EActionTest04.js \
../scripts/Edit/Esc/Tests/EActionTest05.js \
../scripts/Edit/Esc/Tests/EActionTest06.js \
../scripts/Edit/Esc/Tests/EActionTest07.js \
../scripts/Edit/Esc/Tests/EActionTest08.js \
../scripts/Edit/Paste/Paste.js \
../scripts/Edit/Paste/PasteInit.js \
../scripts/Edit/Paste/Tests/PasteTest00.js \
../scripts/Edit/Paste/Tests/PasteTest01.js \
../scripts/Edit/Paste/Tests/PasteTest02.js \
../scripts/Edit/Redo/Redo.js \
../scripts/Edit/Redo/RedoInit.js \
../scripts/Edit/Undo/Undo.js \
../scripts/Edit/Undo/UndoInit.js \
../scripts/File/AutoSave/AutoSave.js \
../scripts/File/BitmapExport/BitmapExport.js \
../scripts/File/BitmapExport/BitmapExportInit.js \
../scripts/File/BitmapExport/BitmapExportWorker.js \
../scripts/File/CloseFile/CloseFile.js \
../scripts/File/CloseFile/CloseFileInit.js \
../scripts/File/File.js \
../scripts/File/ImportFile/ImportFile.js \
../scripts/File/ImportFile/ImportFileInit.js \
../scripts/File/NewFile/NewFile.js \
../scripts/File/NewFile/NewFileInit.js \
../scripts/File/OpenFile/OpenFile.js \
../scripts/File/OpenFile/OpenFileInit.js \
../scripts/File/PdfExport/PdfExport.js \
../scripts/File/PdfExport/PdfExportInit.js \
../scripts/File/Print/Print.js \
../scripts/File/Print/PrintInit.js \
../scripts/File/PrintCurrentView/PrintCurrentView.js \
../scripts/File/PrintCurrentView/PrintCurrentViewInit.js \
../scripts/File/PrintPreview/PrintPreview.js \
../scripts/File/PrintPreview/PrintPreviewInit.js \
../scripts/File/Quit/Quit.js \
../scripts/File/Quit/QuitInit.js \
../scripts/File/RecentFiles/RecentFiles.js \
../scripts/File/RecentFiles/RecentFilesInit.js \
../scripts/File/Save/Save.js \
../scripts/File/Save/SaveInit.js \
../scripts/File/SaveAs/SaveAs.js \
../scripts/File/SaveAs/SaveAsInit.js \
../scripts/File/SvgImport/SvgImport.js \
../scripts/File/SvgImport/SvgImportInit.js \
../scripts/Help/About/About.js \
../scripts/Help/About/AboutCredits.js \
../scripts/Help/About/AboutInit.js \
../scripts/Help/BrowseUserManual/BrowseUserManual.js \
../scripts/Help/BrowseUserManual/BrowseUserManualInit.js \
../scripts/Help/CheckForUpdates/CheckForUpdates.js \
../scripts/Help/CheckForUpdates/CheckForUpdatesInit.js \
../scripts/Help/CheckForUpdates/CheckForUpdatesPostInit.js \
../scripts/Help/FAQ/FAQ.js \
../scripts/Help/FAQ/FAQInit.js \
../scripts/Help/Forum/Forum.js \
../scripts/Help/Forum/ForumInit.js \
../scripts/Help/Help.js \
../scripts/Help/ReportBug/ReportBug.js \
../scripts/Help/ReportBug/ReportBugInit.js \
../scripts/Help/ReportTranslationError/ReportTranslationError.js \
../scripts/Help/ReportTranslationError/ReportTranslationErrorInit.js \
../scripts/Help/ShowReadme/ShowReadme.js \
../scripts/Help/ShowReadme/ShowReadmeInit.js \
../scripts/Help/Website/Website.js \
../scripts/Help/Website/WebsiteInit.js \
../scripts/ImportExport/SvgImporter/SvgImporter.js \
../scripts/ImportExport/SvgImporter/SvgImporterInit.js \
../scripts/Information/InfoAngle/InfoAngle.js \
../scripts/Information/InfoAngle/InfoAngleInit.js \
../scripts/Information/InfoArcCircleArea/InfoArcCircleArea.js \
../scripts/Information/InfoArcCircleArea/InfoArcCircleAreaInit.js \
../scripts/Information/InfoArea/InfoArea.js \
../scripts/Information/InfoArea/InfoAreaInit.js \
../scripts/Information/InfoDistanceEE/InfoDistanceEE.js \
../scripts/Information/InfoDistanceEE/InfoDistanceEEInit.js \
../scripts/Information/InfoDistanceEE/Tests/InfoDistanceEETest00.js \
../scripts/Information/InfoDistanceEE/Tests/InfoDistanceEETest01.js \
../scripts/Information/InfoDistanceEE/Tests/InfoDistanceEETest02.js \
../scripts/Information/InfoDistanceEE/Tests/InfoDistanceEETest03.js \
../scripts/Information/InfoDistanceEE/Tests/InfoDistanceEETest04.js \
../scripts/Information/InfoDistanceEP/InfoDistanceEP.js \
../scripts/Information/InfoDistanceEP/InfoDistanceEPInit.js \
../scripts/Information/InfoDistanceEP/Tests/InfoDistanceEPTest00.js \
../scripts/Information/InfoDistancePP/InfoDistancePP.js \
../scripts/Information/InfoDistancePP/InfoDistancePPInit.js \
../scripts/Information/InfoDistancePP/Tests/InfoDistancePPTest00.js \
../scripts/Information/InfoPolylineArea/InfoPolylineArea.js \
../scripts/Information/InfoPolylineArea/InfoPolylineAreaInit.js \
../scripts/Information/InfoPosition/InfoPosition.js \
../scripts/Information/InfoPosition/InfoPositionInit.js \
../scripts/Information/InfoPositionPol/InfoPositionPol.js \
../scripts/Information/InfoPositionPol/InfoPositionPolInit.js \
../scripts/Information/InfoPositionPolRel/InfoPositionPolRel.js \
../scripts/Information/InfoPositionPolRel/InfoPositionPolRelInit.js \
../scripts/Information/InfoPositionRel/InfoPositionRel.js \
../scripts/Information/InfoPositionRel/InfoPositionRelInit.js \
../scripts/Information/Information.js \
../scripts/Layer/AddLayer/AddLayer.js \
../scripts/Layer/AddLayer/AddLayerInit.js \
../scripts/Layer/AddLayer/Tests/AddLayerTest00.js \
../scripts/Layer/AddLayer/Tests/AddLayerTest01.js \
../scripts/Layer/AddLayer/Tests/AddLayerTest02.js \
../scripts/Layer/DeselectLayer/DeselectLayer.js \
../scripts/Layer/DeselectLayer/DeselectLayerInit.js \
../scripts/Layer/EditLayer/EditLayer.js \
../scripts/Layer/EditLayer/EditLayerInit.js \
../scripts/Layer/HideAllLayers/HideAllLayers.js \
../scripts/Layer/HideAllLayers/HideAllLayersInit.js \
../scripts/Layer/HierarchicalLayers.js \
../scripts/Layer/Layer.js \
../scripts/Layer/LayerDialog.js \
../scripts/Layer/LockAllLayers/LockAllLayers.js \
../scripts/Layer/LockAllLayers/LockAllLayersInit.js \
../scripts/Layer/RemoveLayer/RemoveLayer.js \
../scripts/Layer/RemoveLayer/RemoveLayerInit.js \
../scripts/Layer/SelectLayer/SelectLayer.js \
../scripts/Layer/SelectLayer/SelectLayerInit.js \
../scripts/Layer/ShowActiveLayer/ShowActiveLayer.js \
../scripts/Layer/ShowActiveLayer/ShowActiveLayerInit.js \
../scripts/Layer/ShowAllLayers/ShowAllLayers.js \
../scripts/Layer/ShowAllLayers/ShowAllLayersInit.js \
../scripts/Layer/ToggleLayerLock/ToggleLayerLock.js \
../scripts/Layer/ToggleLayerLock/ToggleLayerLockInit.js \
../scripts/Layer/ToggleLayerVisibility/Tests/ToggleLayerVisibilityTest00.js \
../scripts/Layer/ToggleLayerVisibility/ToggleLayerVisibility.js \
../scripts/Layer/ToggleLayerVisibility/ToggleLayerVisibilityInit.js \
../scripts/Layer/UnlockAllLayers/UnlockAllLayers.js \
../scripts/Layer/UnlockAllLayers/UnlockAllLayersInit.js \
../scripts/Misc/Examples/BlockExamples/BlockExamples.js \
../scripts/Misc/Examples/BlockExamples/ExAddBlock/ExAddBlock.js \
../scripts/Misc/Examples/CommandLineExamples/CommandLineExamples.js \
../scripts/Misc/Examples/CommandLineExamples/ExSetColor/ExSetColor.js \
../scripts/Misc/Examples/DrawExamples/DrawExamples.js \
../scripts/Misc/Examples/DrawExamples/ExDrawColors/ExDrawColors.js \
../scripts/Misc/Examples/DrawExamples/ExDrawFonts/ExDrawFonts.js \
../scripts/Misc/Examples/DrawExamples/ExLineDove/ExLineDove.js \
../scripts/Misc/Examples/DrawExamples/ExLineDove/ExLineDoveInit.js \
../scripts/Misc/Examples/DrawExamples/ExText/ExText.js \
../scripts/Misc/Examples/DrawExamples/ExThreePoints/ExThreePoints.js \
../scripts/Misc/Examples/ExMinimal/ExMinimal.js \
../scripts/Misc/Examples/ExMinimal2/ExMinimal2.js \
../scripts/Misc/Examples/Examples.js \
../scripts/Misc/Examples/IOExamples/ExDumpPolyline/ExDumpPolyline.js \
../scripts/Misc/Examples/IOExamples/ExRegisterFileExporter/ExRegisterFileExporter.js \
../scripts/Misc/Examples/IOExamples/ExRegisterFileImporter/ExRegisterFileImporter.js \
../scripts/Misc/Examples/IOExamples/ExXmlExport/ExXmlExport.js \
../scripts/Misc/Examples/IOExamples/ExXmlExport/ExXmlExportInit.js \
../scripts/Misc/Examples/IOExamples/ExXmlImport/ExXmlImport.js \
../scripts/Misc/Examples/IOExamples/ExXmlImport/ExXmlImportInit.js \
../scripts/Misc/Examples/IOExamples/IOExamples.js \
../scripts/Misc/Examples/IOExamples/_AutoLoadInitFileDialog/AutoLoadInitFileDialog.js \
../scripts/Misc/Examples/LayerExamples/ExAddLayer/ExAddLayer.js \
../scripts/Misc/Examples/LayerExamples/ExLayerCustomProperty/ExLayerCustomProperty.js \
../scripts/Misc/Examples/LayerExamples/LayerExamples.js \
../scripts/Misc/Examples/ListenerExamples/ExExportListener/ExExportListener.js \
../scripts/Misc/Examples/ListenerExamples/ExTransactionListener/ExTransactionListener.js \
../scripts/Misc/Examples/ListenerExamples/ListenerExamples.js \
../scripts/Misc/Examples/MathExamples/ExMandelbrot/ExMandelbrot.js \
../scripts/Misc/Examples/MathExamples/ExMathSpiral/ExMathSpiral.js \
../scripts/Misc/Examples/MathExamples/FlexPainter/FlexPainter.js \
../scripts/Misc/Examples/MathExamples/MathExamples.js \
../scripts/Misc/Examples/ModifyExamples/ExDeleteObject/ExDeleteObject.js \
../scripts/Misc/Examples/ModifyExamples/ModifyExamples.js \
../scripts/Misc/Examples/QtExamples/ExDirListing/ExDirListing.js \
../scripts/Misc/Examples/QtExamples/ExMainWindow/ExMainWindow.js \
../scripts/Misc/Examples/QtExamples/ExProcess/ExProcess.js \
../scripts/Misc/Examples/QtExamples/ExResizeWindow/ExResizeWindow.js \
../scripts/Misc/Examples/QtExamples/ExWidget/ExWidget.js \
../scripts/Misc/Examples/QtExamples/ExWidget/MyWidget.js \
../scripts/Misc/Examples/QtExamples/QtExamples.js \
../scripts/Misc/Misc.js \
../scripts/Misc/MiscBlock/BlockFixNames/BlockFixNames.js \
../scripts/Misc/MiscBlock/BlockListAttributes/BlockListAttributes.js \
../scripts/Misc/MiscBlock/BlockListExport/BlockListExport.js \
../scripts/Misc/MiscBlock/MiscBlock.js \
../scripts/Misc/MiscDevelopment/DevDebug/DevDebug.js \
../scripts/Misc/MiscDevelopment/EcmaScriptShell/EcmaScriptShell.js \
../scripts/Misc/MiscDevelopment/MiscDevelopment.js \
../scripts/Misc/MiscDevelopment/RunScript/RunScript.js \
../scripts/Misc/MiscDevelopment/RunScript/RunScriptInit.js \
../scripts/Misc/MiscDraw/Counter/Counter.js \
../scripts/Misc/MiscDraw/Counter/CounterInit.js \
../scripts/Misc/MiscDraw/Counter/numeral.js \
../scripts/Misc/MiscDraw/Cross/Cross.js \
../scripts/Misc/MiscDraw/Cross/CrossInit.js \
../scripts/Misc/MiscDraw/DrawBoundingBox/DrawBoundingBox.js \
../scripts/Misc/MiscDraw/LineBoxJoint/LineBoxJoint.js \
../scripts/Misc/MiscDraw/LineBoxJoint/LineBoxJointInit.js \
../scripts/Misc/MiscDraw/LineDove/LineDove.js \
../scripts/Misc/MiscDraw/LineDove/LineDoveInit.js \
../scripts/Misc/MiscDraw/LineRadicalAxis/LineRadicalAxis.js \
../scripts/Misc/MiscDraw/LineRadicalAxis/LineRadicalAxisInit.js \
../scripts/Misc/MiscDraw/LineSimilarityAxes/LineSimilarityAxes.js \
../scripts/Misc/MiscDraw/LineSimilarityAxes/LineSimilarityAxesInit.js \
../scripts/Misc/MiscDraw/MiscDraw.js \
../scripts/Misc/MiscDraw/PointPole/PointPole.js \
../scripts/Misc/MiscDraw/PointPole/PointPoleInit.js \
../scripts/Misc/MiscDraw/PointPowerCenter/PointPowerCenter.js \
../scripts/Misc/MiscDraw/PointPowerCenter/PointPowerCenterInit.js \
../scripts/Misc/MiscDraw/TextAlong/TextAlong.js \
../scripts/Misc/MiscDraw/TextAlong/TextAlongInit.js \
../scripts/Misc/MiscDraw/XLineHorizontal/XLineHorizontal.js \
../scripts/Misc/MiscDraw/XLineHorizontal/XLineHorizontalInit.js \
../scripts/Misc/MiscDraw/XLineVertical/XLineVertical.js \
../scripts/Misc/MiscDraw/XLineVertical/XLineVerticalInit.js \
../scripts/Misc/MiscIO/ImportPoints/ImportPoints.js \
../scripts/Misc/MiscIO/MiscIO.js \
../scripts/Misc/MiscIO/MolImport/MolImport.js \
../scripts/Misc/MiscIO/MolImport/MolImportInit.js \
../scripts/Misc/MiscIO/MolImport/MolImporter.js \
../scripts/Misc/MiscModify/ChangeFontToArial/ChangeFontToArial.js \
../scripts/Misc/MiscModify/FlushBackLog/FlushBackLog.js \
../scripts/Misc/MiscModify/MiscModify.js \
../scripts/Misc/MiscModify/ReloadLinetypes/ReloadLinetypes.js \
../scripts/Misc/MiscModify/SplineToLine/SplineToLine.js \
../scripts/Misc/MiscSelect/MiscSelect.js \
../scripts/Misc/MiscSelect/SelectByColor/SelectByColor.js \
../scripts/Misc/MiscSelect/SelectByColor/SelectByColorInit.js \
../scripts/Misc/MiscSelect/SelectByHandle/SelectByHandle.js \
../scripts/Misc/MiscSelect/SelectByHandle/SelectByHandleInit.js \
../scripts/Misc/Screencast/ScMirrored/ScMirrored.js \
../scripts/Misc/Screencast/ScMirrored/ScMirroredInit.js \
../scripts/Misc/Screencast/ScPrepare/ScPrepare.js \
../scripts/Misc/Screencast/ScPrepare/ScPrepareInit.js \
../scripts/Misc/Screencast/Screencast.js \
../scripts/Misc/Tutorials/CommandLineTools/CommandLineTools.js \
../scripts/Misc/Tutorials/CommandLineTools/CreatingDrawing/CreatingDrawing.js \
../scripts/Misc/Tutorials/CommandLineTools/ExPdfExport/ExPdfExport.js \
../scripts/Misc/Tutorials/CommandLineTools/ExSvgExport/ExSvgExport.js \
../scripts/Misc/Tutorials/LibraryBrowserScripts/CubeCuttingOut.js \
../scripts/Misc/Tutorials/MenusAndToolBars/MenusAndToolBars.js \
../scripts/Misc/Tutorials/MenusAndToolBars/MyAction.js \
../scripts/Misc/Tutorials/MenusAndToolBars/MyScripts.js \
../scripts/Misc/Tutorials/PersistentWidgets/PersistentWidgets.js \
../scripts/Misc/Tutorials/Tutorials.js \
../scripts/Modify/AutoTrim/AutoTrim.js \
../scripts/Modify/AutoTrim/AutoTrimInit.js \
../scripts/Modify/AutoTrim/Tests/AutoTrimTest00.js \
../scripts/Modify/AutoTrim/Tests/AutoTrimTest01.js \
../scripts/Modify/AutoTrim/Tests/AutoTrimTest02.js \
../scripts/Modify/AutoTrim/Tests/AutoTrimTest03.js \
../scripts/Modify/AutoTrim/Tests/AutoTrimTest04.js \
../scripts/Modify/AutoTrim/Tests/AutoTrimTest05.js \
../scripts/Modify/AutoTrim/Tests/AutoTrimTest06.js \
../scripts/Modify/AutoTrim/Tests/AutoTrimTest07.js \
../scripts/Modify/AutoTrim/Tests/AutoTrimTest08.js \
../scripts/Modify/AutoTrim/Tests/AutoTrimTest09.js \
../scripts/Modify/Bevel/Bevel.js \
../scripts/Modify/Bevel/BevelInit.js \
../scripts/Modify/Bevel/Tests/BevelTest00.js \
../scripts/Modify/Bevel/Tests/BevelTest01.js \
../scripts/Modify/Bevel/Tests/BevelTest02.js \
../scripts/Modify/Bevel/Tests/BevelTest03.js \
../scripts/Modify/Bevel/Tests/BevelTest04.js \
../scripts/Modify/Bevel/Tests/BevelTest05.js \
../scripts/Modify/Bevel/Tests/BevelTest06.js \
../scripts/Modify/Bevel/Tests/BevelTest07.js \
../scripts/Modify/BreakOut/BreakOut.js \
../scripts/Modify/BreakOut/BreakOutInit.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest00.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest01.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest02.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest03.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest04.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest05.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest06.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest07.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest08.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest09.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest10.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest11.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest12.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest13.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest14.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest15.js \
../scripts/Modify/BreakOut/Tests/BreakOutTest16.js \
../scripts/Modify/BreakOutGap/BreakOutGap.js \
../scripts/Modify/BreakOutGap/BreakOutGapInit.js \
../scripts/Modify/BreakOutGap/Tests/BreakOutGapTest01.js \
../scripts/Modify/BreakOutManual/BreakOutManual.js \
../scripts/Modify/BreakOutManual/BreakOutManualInit.js \
../scripts/Modify/BreakOutManual/Tests/BreakOutManualTest00.js \
../scripts/Modify/BreakOutManual/Tests/BreakOutManualTest01.js \
../scripts/Modify/BreakOutManual/Tests/BreakOutManualTest02.js \
../scripts/Modify/BreakOutManual/Tests/BreakOutManualTest03.js \
../scripts/Modify/Divide/Divide.js \
../scripts/Modify/Divide/DivideInit.js \
../scripts/Modify/Divide/Tests/DivideTest01.js \
../scripts/Modify/Divide/Tests/DivideTest02.js \
../scripts/Modify/DrawOrder/DrawOrder.js \
../scripts/Modify/DrawOrder/ToBack/ToBack.js \
../scripts/Modify/DrawOrder/ToBack/ToBackInit.js \
../scripts/Modify/DrawOrder/ToFront/ToFront.js \
../scripts/Modify/DrawOrder/ToFront/ToFrontInit.js \
../scripts/Modify/EditHatch/EditHatch.js \
../scripts/Modify/EditHatch/EditHatchInit.js \
../scripts/Modify/EditText/EditText.js \
../scripts/Modify/EditText/EditTextInit.js \
../scripts/Modify/Explode/Explode.js \
../scripts/Modify/Explode/ExplodeInit.js \
../scripts/Modify/Explode/Tests/ExplodeTest00.js \
../scripts/Modify/Explode/Tests/ExplodeTest01.js \
../scripts/Modify/Explode/Tests/ExplodeTest02.js \
../scripts/Modify/Explode/Tests/ExplodeTest03.js \
../scripts/Modify/Explode/Tests/ExplodeTest04.js \
../scripts/Modify/Explode/Tests/ExplodeTest05.js \
../scripts/Modify/FlipHorizontal/FlipHorizontal.js \
../scripts/Modify/FlipHorizontal/FlipHorizontalInit.js \
../scripts/Modify/FlipHorizontal/Tests/FlipHorizontalTest00.js \
../scripts/Modify/FlipVertical/FlipVertical.js \
../scripts/Modify/FlipVertical/FlipVerticalInit.js \
../scripts/Modify/FlipVertical/Tests/FlipVerticalTest00.js \
../scripts/Modify/Lengthen/Lengthen.js \
../scripts/Modify/Lengthen/LengthenInit.js \
../scripts/Modify/Lengthen/Tests/LengthenTest00.js \
../scripts/Modify/Lengthen/Tests/LengthenTest01.js \
../scripts/Modify/Lengthen/Tests/LengthenTest02.js \
../scripts/Modify/Lengthen/Tests/LengthenTest03.js \
../scripts/Modify/Mirror/Mirror.js \
../scripts/Modify/Mirror/MirrorInit.js \
../scripts/Modify/Mirror/Tests/MirrorTest00.js \
../scripts/Modify/Mirror/Tests/MirrorTest01.js \
../scripts/Modify/Modify.js \
../scripts/Modify/ModifyCorner.js \
../scripts/Modify/Offset/Offset.js \
../scripts/Modify/Offset/OffsetInit.js \
../scripts/Modify/Offset/Tests/OffsetTest00.js \
../scripts/Modify/Offset/Tests/OffsetTest01.js \
../scripts/Modify/Offset/Tests/OffsetTest02.js \
../scripts/Modify/OffsetThrough/OffsetThrough.js \
../scripts/Modify/OffsetThrough/OffsetThroughInit.js \
../scripts/Modify/Reverse/Reverse.js \
../scripts/Modify/Reverse/ReverseInit.js \
../scripts/Modify/Reverse/Tests/ReverseTest00.js \
../scripts/Modify/Rotate/Rotate.js \
../scripts/Modify/Rotate/RotateInit.js \
../scripts/Modify/Rotate/Tests/RotateTest00.js \
../scripts/Modify/Rotate/Tests/RotateTest01.js \
../scripts/Modify/Rotate2/Rotate2.js \
../scripts/Modify/Rotate2/Rotate2Init.js \
../scripts/Modify/Rotate2/Tests/Rotate2Test01.js \
../scripts/Modify/Rotate2/Tests/Rotate2Test02.js \
../scripts/Modify/Rotate2/Tests/Rotate2Test03.js \
../scripts/Modify/Rotate2/Tests/Rotate2Test04.js \
../scripts/Modify/Rotate2/Tests/Rotate2Test05.js \
../scripts/Modify/Rotate2/Tests/Rotate2Test06.js \
../scripts/Modify/Round/Round.js \
../scripts/Modify/Round/RoundInit.js \
../scripts/Modify/Round/Tests/RoundTest00.js \
../scripts/Modify/Round/Tests/RoundTest01.js \
../scripts/Modify/Scale/Scale.js \
../scripts/Modify/Scale/ScaleInit.js \
../scripts/Modify/Scale/Tests/ScaleTest00.js \
../scripts/Modify/Scale/Tests/ScaleTest01.js \
../scripts/Modify/Scale/Tests/ScaleTest02.js \
../scripts/Modify/Scale/Tests/ScaleTest03.js \
../scripts/Modify/Scale/Tests/ScaleTest04.js \
../scripts/Modify/Scale/Tests/ScaleTest05.js \
../scripts/Modify/Scale/Tests/ScaleTest06.js \
../scripts/Modify/Scale/Tests/ScaleTest07.js \
../scripts/Modify/Scale/Tests/ScaleTest08.js \
../scripts/Modify/Scale/Tests/ScaleTest09.js \
../scripts/Modify/Stretch/Stretch.js \
../scripts/Modify/Stretch/StretchInit.js \
../scripts/Modify/Stretch/Tests/StretchTest00.js \
../scripts/Modify/Stretch/Tests/StretchTest01.js \
../scripts/Modify/Stretch/Tests/StretchTest02.js \
../scripts/Modify/Stretch/Tests/StretchTest03.js \
../scripts/Modify/Stretch/Tests/StretchTest05.js \
../scripts/Modify/Stretch/Tests/StretchTest06.js \
../scripts/Modify/Stretch/Tests/StretchTest07.js \
../scripts/Modify/Stretch/Tests/StretchTest08.js \
../scripts/Modify/Stretch/Tests/StretchTest09.js \
../scripts/Modify/Stretch/Tests/StretchTest10.js \
../scripts/Modify/Transform.js \
../scripts/Modify/Translate/Tests/TranslateTest00.js \
../scripts/Modify/Translate/Tests/TranslateTest01.js \
../scripts/Modify/Translate/Tests/TranslateTest02.js \
../scripts/Modify/Translate/Translate.js \
../scripts/Modify/Translate/TranslateInit.js \
../scripts/Modify/TranslateRotate/Tests/TranslateRotateTest00.js \
../scripts/Modify/TranslateRotate/Tests/TranslateRotateTest01.js \
../scripts/Modify/TranslateRotate/Tests/TranslateRotateTest02.js \
../scripts/Modify/TranslateRotate/TranslateRotate.js \
../scripts/Modify/TranslateRotate/TranslateRotateInit.js \
../scripts/Modify/Trim/Tests/TrimTest00.js \
../scripts/Modify/Trim/Tests/TrimTest01.js \
../scripts/Modify/Trim/Tests/TrimTest02.js \
../scripts/Modify/Trim/Tests/TrimTest03.js \
../scripts/Modify/Trim/Tests/TrimTest04.js \
../scripts/Modify/Trim/Tests/TrimTest05.js \
../scripts/Modify/Trim/Tests/TrimTest06.js \
../scripts/Modify/Trim/Tests/TrimTest07.js \
../scripts/Modify/Trim/Tests/TrimTest08.js \
../scripts/Modify/Trim/Tests/TrimTest09.js \
../scripts/Modify/Trim/Tests/TrimTest10.js \
../scripts/Modify/Trim/Tests/TrimTest11.js \
../scripts/Modify/Trim/Trim.js \
../scripts/Modify/Trim/TrimInit.js \
../scripts/Modify/TrimBoth/Tests/TrimBothTest00.js \
../scripts/Modify/TrimBoth/Tests/TrimBothTest01.js \
../scripts/Modify/TrimBoth/Tests/TrimBothTest02.js \
../scripts/Modify/TrimBoth/Tests/TrimBothTest03.js \
../scripts/Modify/TrimBoth/Tests/TrimBothTest04.js \
../scripts/Modify/TrimBoth/TrimBoth.js \
../scripts/Modify/TrimBoth/TrimBothInit.js \
../scripts/Navigation/DefaultNavigation/DefaultNavigation.js \
../scripts/Projection/IsometricProjection/IsoProject/IsoProject.js \
../scripts/Projection/IsometricProjection/IsoProject/IsoProjectInit.js \
../scripts/Projection/IsometricProjection/IsoProject/Tests/IsoProjectTest00.js \
../scripts/Projection/IsometricProjection/IsoProject/Tests/IsoProjectTest01.js \
../scripts/Projection/IsometricProjection/IsoProject/Tests/IsoProjectTest03.js \
../scripts/Projection/IsometricProjection/IsoProject/Tests/IsoProjectTest04.js \
../scripts/Projection/IsometricProjection/IsoProject/Tests/IsoProjectTest10.js \
../scripts/Projection/IsometricProjection/IsoProject/Tests/IsoProjectTest11.js \
../scripts/Projection/IsometricProjection/IsometricProjection.js \
../scripts/Projection/Projection.js \
../scripts/Reset/Reset.js \
../scripts/Reset/ResetInit.js \
../scripts/Select/DeselectAll/DeselectAll.js \
../scripts/Select/DeselectAll/DeselectAllInit.js \
../scripts/Select/InvertSelection/InvertSelection.js \
../scripts/Select/InvertSelection/InvertSelectionInit.js \
../scripts/Select/Select.js \
../scripts/Select/SelectAll/SelectAll.js \
../scripts/Select/SelectAll/SelectAllInit.js \
../scripts/Select/SelectContour/SelectContour.js \
../scripts/Select/SelectContour/SelectContourInit.js \
../scripts/Select/SelectIntersectedEntities/SelectIntersectedEntities.js \
../scripts/Select/SelectIntersectedEntities/SelectIntersectedEntitiesInit.js \
../scripts/Select/SelectLayerByEntity/SelectLayerByEntity.js \
../scripts/Select/SelectLayerByEntity/SelectLayerByEntityInit.js \
../scripts/Select/SelectRectangle/SelectRectangle.js \
../scripts/Select/SelectRectangle/SelectRectangleInit.js \
../scripts/ShapeAlgorithms.js \
../scripts/Snap/LockRelativeZero/LockRelativeZero.js \
../scripts/Snap/LockRelativeZero/LockRelativeZeroInit.js \
../scripts/Snap/RestrictAngleLength/RestrictAngleLength.js \
../scripts/Snap/RestrictAngleLength/RestrictAngleLengthInit.js \
../scripts/Snap/RestrictHorizontal/RestrictHorizontal.js \
../scripts/Snap/RestrictHorizontal/RestrictHorizontalInit.js \
../scripts/Snap/RestrictOff/RestrictOff.js \
../scripts/Snap/RestrictOff/RestrictOffInit.js \
../scripts/Snap/RestrictOrthogonal/RestrictOrthogonal.js \
../scripts/Snap/RestrictOrthogonal/RestrictOrthogonalInit.js \
../scripts/Snap/RestrictVertical/RestrictVertical.js \
../scripts/Snap/RestrictVertical/RestrictVerticalInit.js \
../scripts/Snap/SetRelativeZero/SetRelativeZero.js \
../scripts/Snap/SetRelativeZero/SetRelativeZeroInit.js \
../scripts/Snap/Snap.js \
../scripts/Snap/SnapAuto/SnapAuto.js \
../scripts/Snap/SnapAuto/SnapAutoInit.js \
../scripts/Snap/SnapCenter/SnapCenter.js \
../scripts/Snap/SnapCenter/SnapCenterInit.js \
../scripts/Snap/SnapCoordinate/SnapCoordinate.js \
../scripts/Snap/SnapCoordinate/SnapCoordinateInit.js \
../scripts/Snap/SnapCoordinatePolar/SnapCoordinatePolar.js \
../scripts/Snap/SnapCoordinatePolar/SnapCoordinatePolarInit.js \
../scripts/Snap/SnapDistance/SnapDistance.js \
../scripts/Snap/SnapDistance/SnapDistanceInit.js \
../scripts/Snap/SnapDistanceManual/SnapDistanceManual.js \
../scripts/Snap/SnapDistanceManual/SnapDistanceManualInit.js \
../scripts/Snap/SnapDistanceManual/Tests/SnapDistanceManualTest00.js \
../scripts/Snap/SnapEnd/SnapEnd.js \
../scripts/Snap/SnapEnd/SnapEndInit.js \
../scripts/Snap/SnapFree/SnapFree.js \
../scripts/Snap/SnapFree/SnapFreeInit.js \
../scripts/Snap/SnapGrid/SnapGrid.js \
../scripts/Snap/SnapGrid/SnapGridInit.js \
../scripts/Snap/SnapIntersection/SnapIntersection.js \
../scripts/Snap/SnapIntersection/SnapIntersectionInit.js \
../scripts/Snap/SnapIntersection/Tests/SnapIntersectionTest00.js \
../scripts/Snap/SnapIntersection/Tests/SnapIntersectionTest01.js \
../scripts/Snap/SnapIntersection/Tests/SnapIntersectionTest02.js \
../scripts/Snap/SnapIntersection/Tests/SnapIntersectionTest03.js \
../scripts/Snap/SnapIntersection/Tests/SnapIntersectionTest04.js \
../scripts/Snap/SnapIntersection/Tests/SnapIntersectionTest05.js \
../scripts/Snap/SnapIntersectionManual/SnapIntersectionManual.js \
../scripts/Snap/SnapIntersectionManual/SnapIntersectionManualInit.js \
../scripts/Snap/SnapIntersectionManual/Tests/SnapIntersectionManualTest00.js \
../scripts/Snap/SnapMiddle/SnapMiddle.js \
../scripts/Snap/SnapMiddle/SnapMiddleInit.js \
../scripts/Snap/SnapMiddleManual/SnapMiddleManual.js \
../scripts/Snap/SnapMiddleManual/SnapMiddleManualInit.js \
../scripts/Snap/SnapMiddleManual/Tests/SnapMiddleManualTest00.js \
../scripts/Snap/SnapOnEntity/SnapOnEntity.js \
../scripts/Snap/SnapOnEntity/SnapOnEntityInit.js \
../scripts/Snap/SnapPerpendicular/SnapPerpendicular.js \
../scripts/Snap/SnapPerpendicular/SnapPerpendicularInit.js \
../scripts/Snap/SnapReference/SnapReference.js \
../scripts/Snap/SnapReference/SnapReferenceInit.js \
../scripts/Snap/SnapSelectionCenter/SnapSelectionCenter.js \
../scripts/Snap/SnapSelectionCenter/SnapSelectionCenterInit.js \
../scripts/Snap/SnapTangential/SnapTangential.js \
../scripts/Snap/SnapTangential/SnapTangentialInit.js \
../scripts/Snap/SnapXManual/SnapXManual.js \
../scripts/Snap/SnapXManual/SnapXManualInit.js \
../scripts/Snap/SnapYManual/SnapYManual.js \
../scripts/Snap/SnapYManual/SnapYManualInit.js \
../scripts/Tools/ExTool/ExTool.js \
../scripts/Tools/MergeDrawings/MergeDrawings.js \
../scripts/Tools/MergeDrawings/MergeDrawingsInit.js \
../scripts/Tools/arguments.js \
../scripts/View/AntialiasingMode/AntialiasingMode.js \
../scripts/View/CommandLineFocus/CommandLineFocus.js \
../scripts/View/CommandLineFocus/CommandLineFocusInit.js \
../scripts/View/DisplayDistanceAngle/DisplayDistanceAngle.js \
../scripts/View/DisplayDistanceAngle/DisplayDistanceAngleInit.js \
../scripts/View/DraftMode/DraftMode.js \
../scripts/View/IsometricView/IsometricGridLeft/IsometricGridLeft.js \
../scripts/View/IsometricView/IsometricGridOff/IsometricGridOff.js \
../scripts/View/IsometricView/IsometricGridRight/IsometricGridRight.js \
../scripts/View/IsometricView/IsometricGridTop/IsometricGridTop.js \
../scripts/View/IsometricView/IsometricView.js \
../scripts/View/LinetypeMode/LinetypeMode.js \
../scripts/View/OptionsToolBarFocus/OptionsToolBarFocus.js \
../scripts/View/OptionsToolBarFocus/OptionsToolBarFocusInit.js \
../scripts/View/ShowToolDialog/ShowToolDialog.js \
../scripts/View/ToggleGrid/ToggleGrid.js \
../scripts/View/ToolMatrixFocus/ToolMatrixFocus.js \
../scripts/View/ToolMatrixFocus/ToolMatrixFocusInit.js \
../scripts/View/View.js \
../scripts/View/ViewToolBars/ViewToolBars.js \
../scripts/View/ViewToolBars/ViewToolBarsPostInit.js \
../scripts/View/Zoom/AutoZoom/AutoZoom.js \
../scripts/View/Zoom/AutoZoom/AutoZoomInit.js \
../scripts/View/Zoom/PanZoom/PanZoom.js \
../scripts/View/Zoom/PanZoom/PanZoomInit.js \
../scripts/View/Zoom/PreviousView/PreviousView.js \
../scripts/View/Zoom/PreviousView/PreviousViewInit.js \
../scripts/View/Zoom/WindowZoom/WindowZoom.js \
../scripts/View/Zoom/WindowZoom/WindowZoomInit.js \
../scripts/View/Zoom/Zoom.js \
../scripts/View/Zoom/ZoomIn/ZoomIn.js \
../scripts/View/Zoom/ZoomIn/ZoomInInit.js \
../scripts/View/Zoom/ZoomOut/ZoomOut.js \
../scripts/View/Zoom/ZoomOut/ZoomOutInit.js \
../scripts/View/Zoom/ZoomToSelection/ZoomToSelection.js \
../scripts/View/Zoom/ZoomToSelection/ZoomToSelectionInit.js \
../scripts/WidgetFactory.js \
../scripts/Widgets/AutoZoomView/AutoZoomView.js \
../scripts/Widgets/BlockList/BlockList.js \
../scripts/Widgets/CadToolBar/CadToolBar.js \
../scripts/Widgets/CadToolBar/CadToolBarPanel.js \
../scripts/Widgets/CadToolBar/ColumnLayout.js \
../scripts/Widgets/CadToolMatrix/CadToolMatrix.js \
../scripts/Widgets/CommandLine/CommandLine.js \
../scripts/Widgets/CoordinateDisplay/CoordinateDisplay.js \
../scripts/Widgets/DirectoryList/DirectoryList.js \
../scripts/Widgets/FirstStart/FirstStart.js \
../scripts/Widgets/FirstStart/FirstStartInit.js \
../scripts/Widgets/LayerList/LayerList.js \
../scripts/Widgets/LibraryBrowser/Favorites.js \
../scripts/Widgets/LibraryBrowser/FileIconProvider.js \
../scripts/Widgets/LibraryBrowser/ItemDelegate.js \
../scripts/Widgets/LibraryBrowser/LibraryBrowser.js \
../scripts/Widgets/LibraryBrowser/LibraryBrowserInit.js \
../scripts/Widgets/LibraryBrowser/LibraryBrowserPostInit.js \
../scripts/Widgets/LibraryBrowser/ListViewEventHandler.js \
../scripts/Widgets/LibraryBrowser/Rdf.js \
../scripts/Widgets/LibraryBrowser/db/Item.js \
../scripts/Widgets/LibraryBrowser/db/ItemPeer.js \
../scripts/Widgets/LibraryBrowser/db/ItemTag.js \
../scripts/Widgets/LibraryBrowser/db/ItemTagPeer.js \
../scripts/Widgets/LibraryBrowser/db/Locale.js \
../scripts/Widgets/LibraryBrowser/db/LocalePeer.js \
../scripts/Widgets/LibraryBrowser/db/Table.js \
../scripts/Widgets/LibraryBrowser/db/Tag.js \
../scripts/Widgets/LibraryBrowser/db/TagCategory.js \
../scripts/Widgets/LibraryBrowser/db/TagCategoryPeer.js \
../scripts/Widgets/LibraryBrowser/db/TagPeer.js \
../scripts/Widgets/MenuBar/MenuBar.js \
../scripts/Widgets/MouseDisplay/MouseDisplay.js \
../scripts/Widgets/OptionsToolBar/OptionsToolBar.js \
../scripts/Widgets/PenToolBar/PenToolBar.js \
../scripts/Widgets/ProgressBar/ProgressBar.js \
../scripts/Widgets/PropertyEditor/PropertyEditor.js \
../scripts/Widgets/SelectionDisplay/SelectionDisplay.js \
../scripts/Widgets/StatusBar/StatusBar.js \
../scripts/Widgets/TabBar/TabBar.js \
../scripts/Widgets/ToolBarContextMenu/ToolBarContextMenu.js \
../scripts/Widgets/ViewportWidget/ViewportWidget.js \
../scripts/Widgets/Widgets.js \
../scripts/Window/CloseAll/CloseAll.js \
../scripts/Window/CloseAll/CloseAllInit.js \
../scripts/Window/NextWindow/NextWindow.js \
../scripts/Window/NextWindow/NextWindowInit.js \
../scripts/Window/PreviousWindow/PreviousWindow.js \
../scripts/Window/PreviousWindow/PreviousWindowInit.js \
../scripts/Window/Window.js \
../scripts/autostart.js \
../scripts/date.js \
../scripts/input.js \
../scripts/lib/date.format.js \
../scripts/lib/hull/grid.js \
../scripts/lib/hull/hull.js \
../scripts/lib/hull/intersect.js \
../scripts/lib/sprintf2/sprintf2.js \
../scripts/library.js \
../scripts/map.js \
../scripts/simple.js \
../scripts/simple_create.js \
../scripts/simple_info.js \
../scripts/simple_input.js \
../scripts/simple_modify.js \
../scripts/simple_transaction.js \
../scripts/simple_view.js \
../scripts/sprintf.js \
../scripts/Block/BlockDialog.ui \
../scripts/Block/InsertBlock/InsertBlock.ui \
../scripts/Block/InsertBlock/InsertBlockDialog.ui \
../scripts/Block/InsertBlockItem/InsertBlockItem.ui \
../scripts/Draw/Arc/Arc2PA/Arc2PA.ui \
../scripts/Draw/Arc/Arc2PH/Arc2PH.ui \
../scripts/Draw/Arc/Arc2PL/Arc2PL.ui \
../scripts/Draw/Arc/Arc2PR/Arc2PR.ui \
../scripts/Draw/Arc/ArcCPA/ArcCPA.ui \
../scripts/Draw/Arc/ArcConcentric/ArcConcentric.ui \
../scripts/Draw/Arc/ArcConcentricThrough/ArcConcentricThrough.ui \
../scripts/Draw/Arc/ArcTPR/ArcTPR.ui \
../scripts/Draw/Arc/ArcTangential/ArcTangential.ui \
../scripts/Draw/Circle/Circle2PR/Circle2PR.ui \
../scripts/Draw/Circle/Circle2TR/Circle2TR.ui \
../scripts/Draw/Circle/CircleCD/CircleCD.ui \
../scripts/Draw/Circle/CircleCD/CircleCDDialog.ui \
../scripts/Draw/Circle/CircleCR/CircleCR.ui \
../scripts/Draw/Circle/CircleCR/CircleCRDialog.ui \
../scripts/Draw/Circle/CircleConcentric/CircleConcentric.ui \
../scripts/Draw/Circle/CircleConcentricThrough/CircleConcentricThrough.ui \
../scripts/Draw/Circle/CircleTPR/CircleTPR.ui \
../scripts/Draw/Dimension/DimAngular/DimAngular.ui \
../scripts/Draw/Dimension/DimRotated/DimRotated.ui \
../scripts/Draw/Dimension/Dimension.ui \
../scripts/Draw/Dimension/DimensionScaleDialog.ui \
../scripts/Draw/Dimension/Leader/Leader.ui \
../scripts/Draw/Ellipse/EllipseArcCPPA/EllipseArcCPPA.ui \
../scripts/Draw/Ellipse/EllipseDD/EllipseDD.ui \
../scripts/Draw/Ellipse/EllipseDD/EllipseDDDialog.ui \
../scripts/Draw/Ellipse/EllipseOffset/EllipseOffset.ui \
../scripts/Draw/Ellipse/EllipseOffsetThrough/EllipseOffsetThrough.ui \
../scripts/Draw/Ellipse/EllipseRR/EllipseRR.ui \
../scripts/Draw/Ellipse/EllipseRR/EllipseRRDialog.ui \
../scripts/Draw/Hatch/HatchDialog.ui \
../scripts/Draw/Image/Image.ui \
../scripts/Draw/Line/Line.ui \
../scripts/Draw/Line/Line2P/Line2P.ui \
../scripts/Draw/Line/LineAngle/LineAngle.ui \
../scripts/Draw/Line/LineBisector/LineBisector.ui \
../scripts/Draw/Line/LineHorizontal/LineHorizontal.ui \
../scripts/Draw/Line/LineOrthogonal/LineOrthogonal.ui \
../scripts/Draw/Line/LineParallel/LineParallel.ui \
../scripts/Draw/Line/LineParallelThrough/LineParallelThrough.ui \
../scripts/Draw/Line/LineRelativeAngle/LineRelativeAngle.ui \
../scripts/Draw/Polyline/DrawPolyline/DrawPolyline.ui \
../scripts/Draw/Shape/Shape.ui \
../scripts/Draw/Shape/ShapePolygonAFCP/ShapePolygonAFCP.ui \
../scripts/Draw/Shape/ShapePolygonAFPP/ShapePolygonAFPP.ui \
../scripts/Draw/Shape/ShapePolygonCP/ShapePolygonCP.ui \
../scripts/Draw/Shape/ShapePolygonPP/ShapePolygonPP.ui \
../scripts/Draw/Shape/ShapeRectanglePP/ShapeRectanglePP.ui \
../scripts/Draw/Shape/ShapeRectangleSize/ShapeRectangleSize.ui \
../scripts/Draw/Shape/ShapeRectangleSize/ShapeRectangleSizeDialog.ui \
../scripts/Draw/Spline/SplineControlPoints/SplineControlPoints.ui \
../scripts/Draw/Text/Text.ui \
../scripts/Draw/Text/TextDialog/CharacterMapDialog.ui \
../scripts/Draw/Text/TextDialog/TextDialog.ui \
../scripts/Edit/AbstractPreferences.ui \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/BehaviorPreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/ColorPreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/FontPreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/GridPreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/GraphicsViewPreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/InputPreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/KeyboardPreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/LanguagePreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/LayerCompatibility/PreferencesPage.ui \
../scripts/Edit/AppPreferences/ScriptingPreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/TextPreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/ThemePreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/ToolBarPreferences/PreferencesPage.ui \
../scripts/Edit/AppPreferences/UiPreferences/PreferencesPage.ui \
../scripts/Edit/ConvertUnit/ConvertUnit.ui \
../scripts/Edit/DrawingPreferences/ColorSettings/PreferencesPage.ui \
../scripts/Edit/DrawingPreferences/DimensionSettings/PreferencesPage.ui \
../scripts/Edit/DrawingPreferences/GridSettings/PreferencesPage.ui \
../scripts/Edit/DrawingPreferences/LinetypeSettings/PreferencesPage.ui \
../scripts/Edit/DrawingPreferences/PageSettings/PreferencesPage.ui \
../scripts/Edit/DrawingPreferences/PointDisplaySettings/PreferencesPage.ui \
../scripts/Edit/DrawingPreferences/UnitSettings/PreferencesPage.ui \
../scripts/Edit/DrawingPreferences/ViewportSettings/PreferencesPage.ui \
../scripts/Edit/Paste/Paste.ui \
../scripts/Edit/Paste/PreferencesPage.ui \
../scripts/File/AutoSave/PreferencesPage.ui \
../scripts/File/BitmapExport/BitmapExportDialog.ui \
../scripts/File/ImportFile/ImportFile.ui \
../scripts/File/NewFile/CloseDialog.ui \
../scripts/File/NewFile/MdiChildEmpty.ui \
../scripts/File/PrintPreview/PrintPreview.ui \
../scripts/File/RecentFiles/PreferencesPage.ui \
../scripts/File/SaveAs/PreferencesPage.ui \
../scripts/File/SvgImport/PreferencesPage.ui \
../scripts/File/SvgImport/SvgImportDialog.ui \
../scripts/Help/About/AboutDialog.ui \
../scripts/Help/CheckForUpdates/CheckForUpdatesDialog.ui \
../scripts/Help/ShowReadme/ShowReadmeDialog.ui \
../scripts/Information/InfoArcCircleArea/InfoArcCircleArea.ui \
../scripts/Information/InfoArea/InfoArea.ui \
../scripts/Information/Information.ui \
../scripts/Layer/AddLayer/PreferencesPage.ui \
../scripts/Layer/LayerDialog.ui \
../scripts/Misc/Examples/ExMinimal2/ExMinimal2.ui \
../scripts/Misc/Examples/MathExamples/FlexPainter/FlexPainterDialog.ui \
../scripts/Misc/Examples/QtExamples/ExResizeWindow/ExResizeWindow.ui \
../scripts/Misc/Examples/QtExamples/ExWidget/MyWidget.ui \
../scripts/Misc/MiscDevelopment/EcmaScriptShell/EcmaScriptShell.ui \
../scripts/Misc/MiscDevelopment/EcmaScriptShell/EcmaScriptShellDialog.ui \
../scripts/Misc/MiscDevelopment/RunScript/RunScriptDialog.ui \
../scripts/Misc/MiscDraw/Counter/Counter.ui \
../scripts/Misc/MiscDraw/Cross/Cross.ui \
../scripts/Misc/MiscDraw/LineBoxJoint/LineBoxJoint.ui \
../scripts/Misc/MiscDraw/LineDove/LineDove.ui \
../scripts/Misc/MiscDraw/LineRadicalAxis/LineRadicalAxis.ui \
../scripts/Misc/MiscDraw/TextAlong/TextAlong.ui \
../scripts/Misc/MiscSelect/SelectByHandle/SelectByHandleDialog.ui \
../scripts/Misc/Tutorials/LibraryBrowserScripts/CubeCuttingOut.ui \
../scripts/Misc/Tutorials/PersistentWidgets/PersistentWidgets.ui \
../scripts/Modify/Bevel/Bevel.ui \
../scripts/Modify/BreakOut/BreakOut.ui \
../scripts/Modify/BreakOutGap/BreakOutGap.ui \
../scripts/Modify/BreakOutManual/BreakOutManual.ui \
../scripts/Modify/Explode/ExplodeDialog.ui \
../scripts/Modify/Explode/PreferencesPage.ui \
../scripts/Modify/Lengthen/Lengthen.ui \
../scripts/Modify/Mirror/Mirror.ui \
../scripts/Modify/Mirror/MirrorDialog.ui \
../scripts/Modify/Mirror/PreferencesPage.ui \
../scripts/Modify/Offset/Offset.ui \
../scripts/Modify/OffsetThrough/OffsetThrough.ui \
../scripts/Modify/Rotate/PreferencesPage.ui \
../scripts/Modify/Rotate/Rotate.ui \
../scripts/Modify/Rotate/RotateDialog.ui \
../scripts/Modify/Rotate2/Rotate2.ui \
../scripts/Modify/Rotate2/Rotate2Dialog.ui \
../scripts/Modify/Round/Round.ui \
../scripts/Modify/Scale/PreferencesPage.ui \
../scripts/Modify/Scale/Scale.ui \
../scripts/Modify/Scale/ScaleDialog.ui \
../scripts/Modify/Translate/PreferencesPage.ui \
../scripts/Modify/Translate/Translate.ui \
../scripts/Modify/Translate/TranslateDialog.ui \
../scripts/Modify/TranslateRotate/TranslateRotate.ui \
../scripts/Modify/TranslateRotate/TranslateRotateDialog.ui \
../scripts/Navigation/DefaultNavigation/PreferencesPage.ui \
../scripts/Projection/IsometricProjection/IsoProject/IsoProject.ui \
../scripts/Select/SelectContour/SelectContour.ui \
../scripts/Select/SelectIntersectedEntities/SelectIntersectedEntities.ui \
../scripts/Select/SelectLayerByEntity/SelectLayerByEntity.ui \
../scripts/Select/SelectRectangle/SelectRectangle.ui \
../scripts/Snap/RestrictAngleLength/RestrictAngleLength.ui \
../scripts/Snap/SnapAuto/PreferencesPage.ui \
../scripts/Snap/SnapCoordinate/SnapCoordinate.ui \
../scripts/Snap/SnapCoordinatePolar/SnapCoordinatePolar.ui \
../scripts/Snap/SnapDistance/SnapDistance.ui \
../scripts/Snap/SnapDistanceManual/SnapDistanceManual.ui \
../scripts/Snap/SnapIntersectionManual/PreferencesPage.ui \
../scripts/Widgets/BlockList/BlockList.ui \
../scripts/Widgets/BlockList/PreferencesPage.ui \
../scripts/Widgets/CadToolBar/PreferencesPage.ui \
../scripts/Widgets/CadToolMatrix/CadToolMatrix.ui \
../scripts/Widgets/CadToolMatrix/PreferencesPage.ui \
../scripts/Widgets/CommandLine/CommandLine.ui \
../scripts/Widgets/CommandLine/PreferencesPage.ui \
../scripts/Widgets/CoordinateDisplay/CoordinateDisplay.ui \
../scripts/Widgets/CoordinateDisplay/PreferencesPage.ui \
../scripts/Widgets/Dialog.ui \
../scripts/Widgets/FirstStart/FirstStartDialog.ui \
../scripts/Widgets/LayerList/LayerList.ui \
../scripts/Widgets/LayerList/PreferencesPage.ui \
../scripts/Widgets/LibraryBrowser/LibraryBrowser.ui \
../scripts/Widgets/LibraryBrowser/PreferencesPage.ui \
../scripts/Widgets/MenuBar/PreferencesPage.ui \
../scripts/Widgets/MouseDisplay/MouseDisplay.ui \
../scripts/Widgets/PenToolBar/PenToolBar.ui \
../scripts/Widgets/ProgressBar/ProgressBar.ui \
../scripts/Widgets/PropertyEditor/AddCustomPropertyDialog.ui \
../scripts/Widgets/PropertyEditor/PreferencesPage.ui \
../scripts/Widgets/PropertyEditor/PropertyEditor.ui \
../scripts/Widgets/SelectionDisplay/SelectionDisplay.ui \
../scripts/Widgets/StatusBar/PreferencesPage.ui \
../scripts/Widgets/TabBar/PreferencesPage.ui \
../scripts/Widgets/ViewportWidget/Templates/00_Single.ui \
../scripts/Widgets/ViewportWidget/Templates/10_TwoVertical.ui \
../scripts/Widgets/ViewportWidget/Templates/11_TwoHorizontal.ui \
../scripts/Widgets/ViewportWidget/Templates/20_ThreeRight.ui \
../scripts/Widgets/ViewportWidget/Templates/21_ThreeLeft.ui \
../scripts/Widgets/ViewportWidget/Templates/22_ThreeAbove.ui \
../scripts/Widgets/ViewportWidget/Templates/23_ThreeBelow.ui \
../scripts/Widgets/ViewportWidget/Templates/24_ThreeVertical.ui \
../scripts/Widgets/ViewportWidget/Templates/25_ThreeHorizontal.ui \
../scripts/Widgets/ViewportWidget/Templates/30_FourEqual.ui \
../scripts/Widgets/ViewportWidget/Templates/31_FourRight.ui \
../scripts/Widgets/ViewportWidget/Templates/32_FourLeft.ui \
../scripts/Widgets/ViewportWidget/ViewportWidgetQt.ui \
