// Auto generated by Testing Dashboard
// File        : scripts/Draw/Arc/ArcTPR/Tests/ArcTPRTest02.js
// Timestamp   : Fri Dec 13 09:08:23 2024
// Description : 

include('scripts/Developer/TestingDashboard/TdbTest.js');

function ArcTPRTest02() {
    TdbTest.call(this, 'scripts/Draw/Arc/ArcTPR/Tests/ArcTPRTest02.js');
}

ArcTPRTest02.prototype = new TdbTest();

ArcTPRTest02.prototype.test00 = function() {
    qDebug('running ArcTPRTest02.test00()...');
    this.setUp();
    this.importFile('scripts/Draw/Arc/ArcTPR/Tests/data/four_solutions.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ArcToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ArcToolsPanel::ArcTPRButton');
    this.setToolOption('ArcTPR/Radius', '80');
    this.updateToolOptions();
    var p = new RVector(109.747438, 52.394013);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(99.759035, -0.012675);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(94.570254, 40.330097);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(75.371764, 33.065804);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(72.388215, 33.065804);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('ArcTPRTest02_000.dxf');
    this.tearDown();
    qDebug('finished ArcTPRTest02.test00()');
};

