/**
 * Copyright (c) 2011-2013 by Andrew Mustun. All rights reserved.
 * 
 * This file is part of the QCAD project.
 *
 * QCAD is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QCAD is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with QCAD.
 */
// Auto generated by Testing Dashboard
// File        : scripts/Modify/Rotate2/Tests/Rotate2Test00.js
// Timestamp   : 2011-08-08 11:09:44
// Description : Rotate 2 using a circle

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function Rotate2Test00() {
    TdbTest.call(this, 'scripts/Modify/Rotate2/Tests/Rotate2Test00.js');
}

Rotate2Test00.prototype = new TdbTest();

Rotate2Test00.prototype.test00 = function() {
    qDebug('running Rotate2Test00.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/Rotate2/Tests/data/circle.dxf');
    var p = new RVector(-5, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.triggerCommand('rotate2');
    this.setToolOption('Rotate2/PrimaryAngle',  [ 30, 0 ] );
    this.setToolOption('Rotate2/SecondaryAngle',  [ -30, 0 ] );
    this.setToolOption('Rotate2/NumberOfCopies',  [ 11, 0 ] );
    this.updateToolOptions();
    var p = new RVector(-10, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(0, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.dlgStart();
    this.dlgAppendCode('var map = new Map()');
    this.dlgAppendCode("map.put('DialogOpenedByTdb/NumberOfCopies',  [ 11, 0 ] )");
    this.dlgAppendCode("map.put('DialogOpenedByTdb/PrimaryAngle',  [ 30, 0 ] )");
    this.dlgAppendCode("map.put('DialogOpenedByTdb/SecondaryAngle',  [ -30, 0 ] )");
    this.dlgAppendCode("map.put('DialogOpenedByTdb/UseCurrentAttributes', false)");
    this.dlgAppendCode("WidgetFactory.restoreState(dialog, 'DialogOpenedByTdb', undefined, false, undefined, map)");
    this.dlgEnd();
    this.verifyDrawing('Rotate2Test00_000.dxf');
    this.tearDown();
    qDebug('finished Rotate2Test00.test00()');
};

