// Auto generated by Testing Dashboard
// File        : scripts/Modify/Stretch/Tests/StretchTest06.js
// Timestamp   : 2019-03-05 20:19:32
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function StretchTest06() {
    TdbTest.call(this, 'scripts/Modify/Stretch/Tests/StretchTest06.js');
}

StretchTest06.prototype = new TdbTest();

StretchTest06.prototype.test00 = function() {
    qDebug('running StretchTest06.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/Stretch/Tests/data/entities2.dxf');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::ModifyToolsPanel::StretchProButton');
    this.setToolOption('StretchPro/Mode', 'RectangleArea');
    this.updateToolOptions();
    var p = new RVector(34.416667, 27.943813);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.MidButton, 4, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.MidButton, 0, 0);
    TdbTest.clickOnWidget('MainWindow::ViewToolBar::ToolButtonZoomOut');
    TdbTest.clickOnWidget('MainWindow::ViewToolBar::ToolButtonZoomOut');
    this.setZoom(6.358381502890174, new RVector(20.7904, 10.8414, 0, true));
    var p = new RVector(-0.816793, -8.954116);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(6.358381502890174, new RVector(20.7904, 10.8414, 0, true));
    var p = new RVector(39.916843, 50.337702);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(6.358381502890174, new RVector(20.7904, 10.8414, 0, true));
    var p = new RVector(0.126843, 50.337702);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(6.358381502890174, new RVector(20.7904, 10.8414, 0, true));
    var p = new RVector(40.074116, 50.023157);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(20.886843, 38.542247);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(21.83048, 38.856793);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('StretchTest06_000.dxf');
    this.tearDown();
    qDebug('finished StretchTest06.test00()');
};

