// Auto generated by Testing Dashboard
// File        : scripts/Modify/TrimBoth/Tests/TrimBothTest01.js
// Timestamp   : 2015-11-04 16:03:27
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function TrimBothTest01() {
    TdbTest.call(this, 'scripts/Modify/TrimBoth/Tests/TrimBothTest01.js');
}

TrimBothTest01.prototype = new TdbTest();

TrimBothTest01.prototype.test00 = function() {
    qDebug('running TrimBothTest01.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/TrimBoth/Tests/data/open_polylines.dxf');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::ModifyToolsPanel::TrimBothButton');
    this.setZoom(5.916897506925208, new RVector(-5.64981, 22.3507, 0, true));
    var p = new RVector(12.241105, 17.366105);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(5.916897506925208, new RVector(-5.64981, 22.3507, 0, true));
    var p = new RVector(16.973315, 12.29588);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(5.916897506925208, new RVector(-5.64981, 22.3507, 0, true));
    var p = new RVector(32.183989, 17.197097);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(5.916897506925208, new RVector(-5.64981, 22.3507, 0, true));
    var p = new RVector(40.465356, 12.802903);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(5.916897506925208, new RVector(-5.64981, 22.3507, 0, true));
    var p = new RVector(51.61985, 20.070225);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(5.916897506925208, new RVector(-5.64981, 22.3507, 0, true));
    var p = new RVector(56.859082, 11.788858);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(5.916897506925208, new RVector(-5.64981, 22.3507, 0, true));
    var p = new RVector(71.562734, 20.239232);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(5.916897506925208, new RVector(-5.64981, 22.3507, 0, true));
    var p = new RVector(81.196161, 12.126873);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(5.916897506925208, new RVector(-5.64981, 22.3507, 0, true));
    var p = new RVector(95.39279, 18.887172);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(5.916897506925208, new RVector(-5.64981, 22.3507, 0, true));
    var p = new RVector(98.941948, 15);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(63.281367, -1.900749);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(63.11236, -2.238764);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(62.098315, -3.590824);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('TrimBothTest01_000.dxf');
    this.tearDown();
    qDebug('finished TrimBothTest01.test00()');
};

