// Auto generated by Testing Dashboard
// File        : scripts/Modify/Trim/Tests/TrimTest10.js
// Timestamp   : 2016-03-08 10:36:05
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function TrimTest10() {
    TdbTest.call(this, 'scripts/Modify/Trim/Tests/TrimTest10.js');
}

TrimTest10.prototype = new TdbTest();

TrimTest10.prototype.test00 = function() {
    qDebug('running TrimTest10.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/Trim/Tests/data/tangent.dxf');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::ModifyToolsPanel::TrimButton');
    this.setZoom(32.66666394444467, new RVector(-6.06122, 2.76531, 0, true));
    var p = new RVector(19.806122, 4.612244);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(32.66666394444467, new RVector(-6.06122, 2.76531, 0, true));
    var p = new RVector(19.653061, 6.265306);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('TrimTest10_000.dxf');
    var p = new RVector(14.60204, 1.704081);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.setZoom(32.66666394444467, new RVector(-6.06122, 2.76531, 0, true));
    var p = new RVector(14.295918, -0.163266);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(32.66666394444467, new RVector(-6.06122, 2.76531, 0, true));
    var p = new RVector(19.867347, 6.173469);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(13.622448, 6.020408);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(13.561224, 6.081632);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(13.469387, 6.112245);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('TrimTest10_001.dxf');
    this.tearDown();
    qDebug('finished TrimTest10.test00()');
};

