// Auto generated by Testing Dashboard
// File        : scripts/Snap/SnapIntersectionManual/Tests/SnapIntersectionManualTest00.js
// Timestamp   : 2016-12-19 10:15:14
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function SnapIntersectionManualTest00() {
    TdbTest.call(this, 'scripts/Snap/SnapIntersectionManual/Tests/SnapIntersectionManualTest00.js');
}

SnapIntersectionManualTest00.prototype = new TdbTest();

SnapIntersectionManualTest00.prototype.test00 = function() {
    qDebug('running SnapIntersectionManualTest00.test00()...');
    this.setUp();
    this.importFile('scripts/Snap/SnapIntersectionManual/Tests/data/intersections_manual.dxf');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::MainToolsPanel::PointToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::PointToolsPanel::Point1PButton');
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::SnapToolsPanel::SnapIntersectionManualButton');
    this.setZoom(11.301587301587302, new RVector(-7.66292, 9.38573, 0, true));
    var p = new RVector(16.599719, 9.638149);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(11.301587301587302, new RVector(-7.66292, 9.38573, 0, true));
    var p = new RVector(29.872191, 16.362868);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::SnapToolsPanel::SnapIntersectionManualButton');
    this.setZoom(11.301587301587302, new RVector(-7.66292, 9.38573, 0, true));
    var p = new RVector(16.511236, 9.638149);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(11.301587301587302, new RVector(-7.66292, 9.38573, 0, true));
    var p = new RVector(33.057584, 8.576351);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::SnapToolsPanel::SnapIntersectionManualButton');
    this.setZoom(11.301587301587302, new RVector(-7.66292, 9.38573, 0, true));
    var p = new RVector(17.042135, 9.549666);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(11.301587301587302, new RVector(-7.66292, 9.38573, 0, true));
    var p = new RVector(41.109551, 10.699947);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::SnapToolsPanel::SnapIntersectionManualButton');
    this.setZoom(11.301587301587302, new RVector(-7.66292, 9.38573, 0, true));
    var p = new RVector(18.457865, 9.3727);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(11.301587301587302, new RVector(-7.66292, 9.38573, 0, true));
    var p = new RVector(46.15309, 13.354441);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    TdbTest.clickOnWidget('MainWindow::CadQToolBar::CadToolBar::SnapToolsPanel::SnapIntersectionManualButton');
    this.setZoom(11.301587301587302, new RVector(-7.66292, 9.38573, 0, true));
    var p = new RVector(18.192416, 9.3727);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(11.301587301587302, new RVector(-7.66292, 9.38573, 0, true));
    var p = new RVector(53.585674, 12.115677);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    var p = new RVector(51.108146, 0.435902);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    var p = new RVector(49.161517, 0.347419);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.RightButton, 2, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.RightButton, 0, 0);
    this.verifyDrawing('SnapIntersectionManualTest00_000.dxf');
    this.tearDown();
    qDebug('finished SnapIntersectionManualTest00.test00()');
};

