/**
 * Copyright (c) 2011-2013 by Andrew Mustun. All rights reserved.
 * 
 * This file is part of the QCAD project.
 *
 * QCAD is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QCAD is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with QCAD.
 */
// Auto generated by Testing Dashboard
// File        : scripts/Modify/Bevel/Tests/BevelTest04.js
// Timestamp   : 2011-07-27 15:54:24
// Description : 

include('scripts/Pro/Developer/TestingDashboard/TdbTest.js');

function BevelTest04() {
    TdbTest.call(this, 'scripts/Modify/Bevel/Tests/BevelTest04.js');
}

BevelTest04.prototype = new TdbTest();

BevelTest04.prototype.test00 = function() {
    qDebug('running BevelTest04.test00()...');
    this.setUp();
    this.importFile('scripts/Modify/Bevel/Tests/data/1line_1arc.dxf');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::MainToolsPanel::ModifyToolsPanelButton');
    TdbTest.clickOnWidget('MainWindow::CadToolBar::ModifyToolsPanel::BevelButton');
    this.setToolOption('Bevel/Trim', 'true');
    this.setToolOption('Bevel/Length1',  [ 10, 0 ] );
    this.setToolOption('Bevel/Length2',  [ 16, 0 ] );
    this.updateToolOptions();
    this.setZoom(22.249448617739205, new RVector(-3.03649, -12.2383, 0) );
    var p = new RVector(13.868216, 25.946498);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.setZoom(22.249448617739205, new RVector(-3.03649, -12.2383, 0) );
    var p = new RVector(20.924571, 24.77793);
    this.sendMouseEventModelPos(QEvent.MouseButtonPress, p, Qt.LeftButton, 1, 0);
    this.sendMouseEventModelPos(QEvent.MouseButtonRelease, p, Qt.LeftButton, 0, 0);
    this.verifyDrawing('BevelTest04_000.dxf');
    this.tearDown();
    qDebug('finished BevelTest04.test00()');
};

